### ISSUE TITLE
Generated incorrect java after saving from "Manual" tab

### ISSUE THREAD

**Issue by djplaistow** [katalon-studio/katalon-studio#138]
#### Operating System: (for example: Windows 10 or OSX Sierra)
Windows 7 Enterprise with Service Pack 1

#### Katalon Studio Version:
Version: 6.1.0
Build: 1
#### Katalon Studio logs:

* Windows logs folder: <Katalon Studio folder>\config\.metadata\.log

* MacOS logs folder: file:///Applications/Katalon%20Studio.app/Contents/MacOS/config/.metadata/.plugins/org.eclipse.ui.workbench/log

#### Environment (for Web testing):

Firefox Quantum 66.0.3 (64-bit)

#### Steps to reproduce:

When creating a test case and using the both the "Manual" tab and "Script" tab, Katalon Studio keeps both in synch. This works very well. However, there is a bug in the following scenario:

In the "Script" tab, I created a test case with the following array:

String[] componentTestObjects = new String[8]
(componentTestObjects[0]) = 'input_Fine Cull 1 Metal_Metal'
(componentTestObjects[1]) = 'input_Pre-ID Tag reader (ICS3)_PreIdTagReader'
(componentTestObjects[2]) = 'input_Pre-ID Tag detection (ACR)_AcrPreIdTagDetect'
(componentTestObjects[3]) = 'input_Doubles Detector_DoublesDetector'
(componentTestObjects[4]) = 'input_Sortcode Printer_SortcodePrinter'
(componentTestObjects[5]) = 'input_ID Tag Printer_IDTagPrinter'
(componentTestObjects[6]) = 'input_Sortcode Verifier_SortcodeVerifier'
(componentTestObjects[7]) = 'input_ID Tag Verifier_IDTagVerifier'

As long as I do not make any further edits in the "Manual" tab, this test case works as desired. If I make an edit in the "Manual" tab, the array is regenerated as:

String[] componentTestObjects = new String[]

(componentTestObjects[0]) = 'input_Fine Cull 1 Metal_Metal'

(componentTestObjects[1]) = 'input_Pre-ID Tag reader (ICS3)_PreIdTagReader'

(componentTestObjects[2]) = 'input_Pre-ID Tag detection (ACR)_AcrPreIdTagDetect'

(componentTestObjects[3]) = 'input_Doubles Detector_DoublesDetector'

(componentTestObjects[4]) = 'input_Sortcode Printer_SortcodePrinter'

(componentTestObjects[5]) = 'input_ID Tag Printer_IDTagPrinter'

(componentTestObjects[6]) = 'input_Sortcode Verifier_SortcodeVerifier'

(componentTestObjects[7]) = 'input_ID Tag Verifier_IDTagVerifier'

Please note the explicit sizing of the array to 8 elements has been removed.

#### Expected Behavior:

I can fix this by going back to the "Script" tab and adding the explicit array length declaration (i.e. the 8) back in. I would expect that the custom code that I added is not rewritten at all. At a bare minimum, it should remain syntactically correct, but I would go further to say that ideally, the whitespace wouldn't even be changed.

#### Actual Behavior:
The removal of the explicit array sizing causes the script to fail with the following error:
04-23-2019 12:45:39 PM callTestCase(findTestCase("Common Test Cases/VerifyComponentEnableStatus"), ["Username":"Engineering"], STOP_ON_FAILURE)

Elapsed time: 0.074s

if (!(callTestCase(findTestCase("Common Test Cases/IsInRun"), [:], STOP_ON_FAILURE))) FAILED.
Reason:
com.kms.katalon.core.exception.StepFailedException: Unable to call Test Case 'Test Cases/Common Test Cases/VerifyComponentEnableStatus' (Root cause: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script1556041539246.groovy: 22: No expression for the array constructor call at line: 22 column: 43. File: script1556041539246.groovy @ line 22, column 43.
   ponentTestObjects = new String[]
                                 ^

1 error

	at com.kms.katalon.core.main.TestCaseMethodNodeCollector.<init>(TestCaseMethodNodeCollector.java:42)
	at com.kms.katalon.core.main.TestCaseExecutor.processScriptPreparationPhase(TestCaseExecutor.java:146)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:205)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:114)
	at com.kms.katalon.core.keyword.builtin.CallTestCaseKeyword$_callTestCase_closure1.doCall(CallTestCaseKeyword.groovy:59)
	at com.kms.katalon.core.keyword.builtin.CallTestCaseKeyword$_callTestCase_closure1.call(CallTestCaseKeyword.groovy)
	at com.kms.katalon.core.keyword.internal.KeywordMain.runKeyword(KeywordMain.groovy:66)
	at com.kms.katalon.core.keyword.builtin.CallTestCaseKeyword.callTestCase(CallTestCaseKeyword.groovy:81)
	at com.kms.katalon.core.keyword.builtin.CallTestCaseKeyword.execute(CallTestCaseKeyword.groovy:44)
	at com.kms.katalon.core.keyword.internal.KeywordExecutor.executeKeywordForPlatform(KeywordExecutor.groovy:56)
	at com.kms.katalon.core.keyword.BuiltinKeywords.callTestCase(BuiltinKeywords.groovy:334)
	at CheckStartRunTab.run(CheckStartRunTab:21)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:331)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:322)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:301)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:293)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:227)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:114)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:105)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1556041494692.run(TempTestCase1556041494692.groovy:21)
)
	at com.kms.katalon.core.keyword.internal.KeywordMain.stepFailed(KeywordMain.groovy:48)
	at com.kms.katalon.core.keyword.internal.KeywordMain.stepFailed(KeywordMain.groovy)
	at com.kms.katalon.core.keyword.internal.KeywordMain.runKeyword(KeywordMain.groovy:68)
	at com.kms.katalon.core.keyword.builtin.CallTestCaseKeyword.callTestCase(CallTestCaseKeyword.groovy:81)
	at com.kms.katalon.core.keyword.builtin.CallTestCaseKeyword.execute(CallTestCaseKeyword.groovy:44)
	at com.kms.katalon.core.keyword.internal.KeywordExecutor.executeKeywordForPlatform(KeywordExecutor.groovy:56)
	at com.kms.katalon.core.keyword.BuiltinKeywords.callTestCase(BuiltinKeywords.groovy:334)
	at CheckStartRunTab.run(CheckStartRunTab:21)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:331)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:322)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:301)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:293)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:227)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:114)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:105)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1556041494692.run(TempTestCase1556041494692.groovy:21)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script1556041539246.groovy: 22: No expression for the array constructor call at line: 22 column: 43. File: script1556041539246.groovy @ line 22, column 43.
   ponentTestObjects = new String[]
                                 ^

1 error

	at com.kms.katalon.core.main.TestCaseMethodNodeCollector.<init>(TestCaseMethodNodeCollector.java:42)
	at com.kms.katalon.core.main.TestCaseExecutor.processScriptPreparationPhase(TestCaseExecutor.java:146)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:205)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:114)
	at com.kms.katalon.core.keyword.builtin.CallTestCaseKeyword$_callTestCase_closure1.doCall(CallTestCaseKeyword.groovy:59)
	at com.kms.katalon.core.keyword.builtin.CallTestCaseKeyword$_callTestCase_closure1.call(CallTestCaseKeyword.groovy)
	at com.kms.katalon.core.keyword.internal.KeywordMain.runKeyword(KeywordMain.groovy:66)
	... 16 more

**Comment by devalex88** [comment]
@duyluonganh Please take a look.

**Comment by djplaistow** [comment]
I am not sure how to "take a look". However, I downloaded that latest Katalon Studio (i.e. Version: 6.1.2 Build: 2). This new version still has the issue. Is there some other way I can check?

**Comment by devalex88** [comment]
> I am not sure how to "take a look". However, I downloaded that latest Katalon Studio (i.e. Version: 6.1.2 Build: 2). This new version still has the issue. Is there some other way I can check?

@djplaistow Sorry for the confusion. My previous comment was for @duyluonganh (KS developer).
