### ISSUE TITLE
Adding step in test case causes Katalon Studio to freeze on linux

### ISSUE THREAD

**Issue by keithds** [katalon-studio/katalon-studio#142]
#### Operating System: 

Ubuntu 18.04 64-bit
openjdk version "1.8.0_191"

#### Katalon Studio Version: 

6.1.2

#### Katalon Studio logs: 
!SESSION 2019-05-01 16:17:16.674 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_191
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64 -data config

!ENTRY org.eclipse.core.resources 2 10035 2019-05-01 16:17:18.240
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.
katalon.versionNumber=6.1.2
katalon.buildNumber=2
Could not find element with Id 'com.kms.katalon.composer.webservice.handledmenuitem.webServiceRequest'
Could not find element with Id 'katalon.composer.objectrepository.handledmenuitem.spyweb'
Could not find element with Id 'com.kms.katalon.composer.mobile.dynamicmenucontribution.ios'
Could not find element with Id 'com.kms.katalon.composer.mobile.dynamicmenucontribution.ios'
Warning: NLS unused message: Key in: com.kms.katalon.composer.project.constants.composerProjectMessages
Warning: NLS unused message: Key in: com.kms.katalon.composer.testcase.constants.composerTestcaseMessages
Warning: NLS missing message: BTN_ADDTESTSUITE in: com.kms.katalon.composer.testcase.constants.composerTestcaseMessages
Warning: NLS unused message: PA_LBL_CREATED_DATE in: com.kms.katalon.composer.testsuite.constants.composerTestsuiteMessages
Warning: NLS unused message: PA_LBL_LAST_UPDATED in: com.kms.katalon.composer.testsuite.constants.composerTestsuiteMessages
Warning: NLS unused message: Key in: com.kms.katalon.composer.objectrepository.constant.composerObjectRepositoryMessages
Warning: NLS missing message: MSG_FORUM_SEARCH in: com.kms.katalon.constants.messages

!ENTRY org.eclipse.jface 2 0 2019-05-01 16:17:29.093
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2019-05-01 16:17:29.093
!MESSAGE A conflict occurred for CTRL+SHIFT+D:
Binding(CTRL+SHIFT+D,
	ParameterizedCommand(Command(org.eclipse.jdt.debug.ui.commands.Display,Display,
		Display result of evaluating selected text,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@62eb918,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow,,,system)
Binding(CTRL+SHIFT+D,
	ParameterizedCommand(Command(com.kms.katalon.composer.execution.command.debug,,
		Debug,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@477bea57,
		[Parameter(com.kms.katalon.composer.execution.runMode,Run Mode,null,true)],,true),[org.eclipse.core.commands.Parameterization@de6e4672]),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,system)

!ENTRY org.eclipse.e4.ui.workbench 4 0 2019-05-01 16:17:41.795
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at com.kms.katalon.composer.webservice.view.ApiQuickStartDialog.createDialogArea(ApiQuickStartDialog.java:82)
	at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:767)
	at org.eclipse.jface.window.Window.create(Window.java:426)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1095)
	at org.eclipse.jface.window.Window.open(Window.java:783)
	at com.kms.katalon.composer.webservice.handlers.OpenApiQuickStartHandler.execute(OpenApiQuickStartHandler.java:74)
	at com.kms.katalon.composer.webservice.handlers.OpenApiQuickStartHandler$1.handleEvent(OpenApiQuickStartHandler.java:44)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4536)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4154)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.kms.katalon.core.application.Application.internalRunGUI(Application.java:119)
	at com.kms.katalon.core.application.Application.runGUI(Application.java:109)
	at com.kms.katalon.core.application.Application.start(Application.java:67)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

#### Environment (for Web testing):

N/A.  Error occurs editing test case.

#### Steps to reproduce:

Open a Test Case (Any test case from a sample project will do)
Click on First Step
Click "+Add" Button
Click down arrow under "Send Request" column in new step
Katalon Studio has now frozen

#### Expected Behavior:

Be able to add a new step in the GUI

#### Actual Behavior:

Katalon Studio freezes

**Comment by mluyun** [comment]
was this resolved? I am encountering the same issue on Linux_64-7.5.5 version. Katalon Studio freezes when i'm in Scripting mode
My OS is Fedora 31
