### ISSUE TITLE
Error when closing Katalon Studio

### ISSUE THREAD

**Issue by dungleonhart** [katalon-studio/katalon-studio#16]
Issue code: KAT-3796
Originally reported at https://forum.katalon.com/discussion/10344/error-when-close-5-8-2 by 
Ilkka Kovalainen

> ## Operating System: (for example: Windows 10 or OSX Sierra)
> 
> Windows10
> 
> ## Katalon Studio Version: 
> 
> 5.8.2
> 
> ## Katalon Studio logs:
> 
> !ENTRY org.eclipse.osgi 4 0 2018-10-24 15:26:17.108
> !MESSAGE Application error
> !STACK 1
> org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTException: Widget is disposed)
>     at org.eclipse.swt.SWT.error(SWT.java:4533)
>     at org.eclipse.swt.SWT.error(SWT.java:4448)
>     at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
>     at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
>     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
>     at org.eclipse.swt.widgets.Display.release(Display.java:3881)
>     at org.eclipse.swt.graphics.Device.dispose(Device.java:298)
>     at com.kms.katalon.core.application.Application.internalRunGUI(Application.java:123)
>     at com.kms.katalon.core.application.Application.runGUI(Application.java:100)
>     at com.kms.katalon.core.application.Application.start(Application.java:60)
>     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
>     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
>     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
>     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
>     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
>     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
>     at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
> Caused by: org.eclipse.swt.SWTException: Widget is disposed
>     at org.eclipse.swt.SWT.error(SWT.java:4533)
>     at org.eclipse.swt.SWT.error(SWT.java:4448)
>     at org.eclipse.swt.SWT.error(SWT.java:4419)
>     at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
>     at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:354)
>     at org.eclipse.swt.widgets.Control.setRedraw(Control.java:3679)
>     at com.kms.katalon.composer.execution.part.LogViewerPart.disposeChildrenFromIndex(LogViewerPart.java:270)
>     at com.kms.katalon.composer.execution.part.LogViewerPart.createLogViewerControl(LogViewerPart.java:255)
>     at com.kms.katalon.composer.execution.part.LogViewerPart.access$32(LogViewerPart.java:254)
>     at com.kms.katalon.composer.execution.part.LogViewerPart$20.run(LogViewerPart.java:1207)
>     at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
>     at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
>     ... 19 more
>     at org.eclipse.swt.SWT.error(SWT.java:4533)
>     at org.eclipse.swt.SWT.error(SWT.java:4448)
> 
> !ENTRY org.eclipse.e4.ui.workbench 4 0 2018-10-24 15:26:17.147
> !MESSAGE FrameworkEvent ERROR
> !STACK 0
> org.eclipse.e4.core.di.InjectionException: org.eclipse.swt.SWTException: Invalid thread access
>     at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
>     at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:966)
>     at org.eclipse.e4.core.internal.di.InjectorImpl.disposed(InjectorImpl.java:426)
>     at org.eclipse.e4.core.internal.di.Requestor.disposed(Requestor.java:154)
>     at org.eclipse.e4.core.internal.contexts.ContextObjectSupplier$ContextInjectionListener.update(ContextObjectSupplier.java:78)
>     at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:111)
>     at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.handleInvalid(TrackableComputationExt.java:74)
>     at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:176)
>     at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:161)
>     at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.dispose(EclipseContextOSGi.java:106)
>     at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.bundleChanged(EclipseContextOSGi.java:139)
>     at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:903)
>     at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
>     at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
>     at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213)
>     at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120)
>     at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112)
>     at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:156)
>     at org.eclipse.osgi.container.Module.publishEvent(Module.java:476)
>     at org.eclipse.osgi.container.Module.doStop(Module.java:634)
>     at org.eclipse.osgi.container.Module.stop(Module.java:498)
>     at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:202)
>     at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:165)
>     at java.lang.Thread.run(Thread.java:748)
> Caused by: org.eclipse.swt.SWTException: Invalid thread access
>     at org.eclipse.swt.SWT.error(SWT.java:4533)
>     at org.eclipse.swt.SWT.error(SWT.java:4448)
>     at org.eclipse.swt.SWT.error(SWT.java:4419)
>     at org.eclipse.swt.widgets.Display.error(Display.java:1262)
>     at org.eclipse.swt.widgets.Display.checkDevice(Display.java:766)
>     at org.eclipse.swt.widgets.Display.removeFilter(Display.java:4129)
>     at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.contextDisposed(MenuManagerRenderer.java:339)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
>     ... 23 more
>     at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:255)
>     at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
>     at org.eclipse.swt.widgets.Display.syncExec(Display.java:4821)
>     at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:211)
>     at com.kms.katalon.composer.execution.part.LogViewerPart.refreshPart(LogViewerPart.java:1193)
>     at com.kms.katalon.composer.execution.part.LogViewerPart.access$29(LogViewerPart.java:1192)
>     at com.kms.katalon.composer.execution.part.LogViewerPart$19.run(LogViewerPart.java:1175)
>     at java.lang.Thread.run(Thread.java:748)
> Caused by: org.eclipse.swt.SWTException: Widget is disposed
>     at org.eclipse.swt.SWT.error(SWT.java:4533)
>     at org.eclipse.swt.SWT.error(SWT.java:4448)
>     at org.eclipse.swt.SWT.error(SWT.java:4419)
>     at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
>     at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:354)
>     at org.eclipse.swt.widgets.Control.setRedraw(Control.java:3679)
>     at com.kms.katalon.composer.execution.part.LogViewerPart.disposeChildrenFromIndex(LogViewerPart.java:270)
>     at com.kms.katalon.composer.execution.part.LogViewerPart.createLogViewerControl(LogViewerPart.java:255)
>     at com.kms.katalon.composer.execution.part.LogViewerPart.access$32(LogViewerPart.java:254)
>     at com.kms.katalon.composer.execution.part.LogViewerPart$20.run(LogViewerPart.java:1207)
>     at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
>     at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
>     at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
>     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
>     at org.eclipse.swt.widgets.Display.release(Display.java:3881)
>     at org.eclipse.swt.graphics.Device.dispose(Device.java:298)
>     at com.kms.katalon.core.application.Application.internalRunGUI(Application.java:123)
>     at com.kms.katalon.core.application.Application.runGUI(Application.java:100)
>     at com.kms.katalon.core.application.Application.start(Application.java:60)
>     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
>     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
>     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
>     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
>     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
>     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
>     at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
> 
> !ENTRY org.eclipse.core.resources 2 10035 2018-10-24 15:26:17.755
> !MESSAGE The workspace will exit with unsaved changes in this session.
> 
> !ENTRY org.eclipse.core.jobs 2 2 2018-10-24 15:26:18.091
> !MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.eclipse.jdt.internal.ui.viewsupport.ProblemMarkerManager$1
> 
> !ENTRY org.eclipse.core.jobs 2 2 2018-10-24 15:26:18.099
> !MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.eclipse.ui.internal.progress.AnimationManager$1
> 
> !ENTRY org.eclipse.core.jobs 2 2 2018-10-24 15:26:18.106
> !MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.eclipse.ui.internal.progress.ProgressViewUpdater$1
> 
> !ENTRY org.eclipse.core.jobs 2 2 2018-10-24 15:26:18.113
> !MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.eclipse.ui.internal.progress.WorkbenchSiteProgressService$SiteUpdateJob
> 
> !ENTRY org.eclipse.core.jobs 2 2 2018-10-24 15:26:18.119
> !MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.eclipse.ui.internal.progress.TaskBarProgressManager$2
> 
> ## Steps to reproduce
> Open Katalon Studio, edit test cases and close program
> 
> ## Actual Behavior
> 
> Error message:
> An error has occurred. See the log file
> c:\Users\xxxxxx\Katalon_Studio_Windows_64-5.8.2\config\.metadata\.log.

**Comment by dungleonhart** [comment]
This has been fixed in Katalon Studio 5.9

**Comment by albertosantini** [comment]
I still see this issue in 5.9.1 build 2.

**Comment by dungleonhart** [comment]
Dear @albertosantini , thanks for your information. Does it still happen in 5.10.1?

**Comment by albertosantini** [comment]
It is ok in `5.10.1`.

Thanks for the effort.

**Comment by abbas224** [comment]
Hi @albertosantini  I am facing the same issue in Katalon Studio version 7.2.1. I am running Katalon Studio on Mac OS version 10.15.3 (19D76). Please help me on this issue.

Here is the error log:

org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.core.runtime.AssertionFailedException: null argument:)
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:255)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4814)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:211)
	at com.kms.katalon.composer.components.services.UISynchronizeService.syncExec(UISynchronizeService.java:26)
	at com.kms.katalon.composer.mobile.objectspy.dialog.MobileObjectSpyDialog$14.refreshTreeElements(MobileObjectSpyDialog.java:825)
	at com.kms.katalon.composer.mobile.objectspy.dialog.MobileObjectSpyDialog$14.run(MobileObjectSpyDialog.java:806)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: org.eclipse.core.runtime.AssertionFailedException: null argument:
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:73)
	at org.eclipse.jface.viewers.StructuredViewer.assertElementsNotNull(StructuredViewer.java:586)
	at org.eclipse.jface.viewers.StructuredViewer.getRawChildren(StructuredViewer.java:1002)
	at org.eclipse.jface.viewers.ColumnViewer.getRawChildren(ColumnViewer.java:701)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1349)
	at org.eclipse.jface.viewers.TreeViewer.getRawChildren(TreeViewer.java:341)
	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:907)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:621)
	at org.eclipse.jface.viewers.AbstractTreeViewer.lambda$0(AbstractTreeViewer.java:817)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:795)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:596)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:766)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalInitializeTree(AbstractTreeViewer.java:1538)
	at org.eclipse.jface.viewers.TreeViewer.internalInitializeTree(TreeViewer.java:772)
	at org.eclipse.jface.viewers.AbstractTreeViewer.lambda$1(AbstractTreeViewer.java:1523)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1458)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:354)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1419)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.preservingSelection(CheckboxTreeViewer.java:409)
	at org.eclipse.jface.viewers.AbstractTreeViewer.inputChanged(AbstractTreeViewer.java:1517)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:286)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1696)
	at com.kms.katalon.composer.mobile.objectspy.dialog.MobileObjectSpyDialog$14$3.run(MobileObjectSpyDialog.java:829)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4032)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3708)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:165)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:369)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:481)
	at com.kms.katalon.composer.mobile.objectspy.dialog.MobileObjectSpyDialog.captureObjectAction(MobileObjectSpyDialog.java:859)
	at com.kms.katalon.composer.mobile.objectspy.dialog.MobileObjectSpyDialog.access$8(MobileObjectSpyDialog.java:783)
	at com.kms.katalon.composer.mobile.objectspy.dialog.MobileObjectSpyDialog$10.widgetSelected(MobileObjectSpyDialog.java:620)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1313)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4080)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3706)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.kms.katalon.core.application.Application.internalRunGUI(Application.java:173)
	at com.kms.katalon.core.application.Application.runGUI(Application.java:163)
	at com.kms.katalon.core.application.Application.start(Application.java:82)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
