### ISSUE TITLE
Unable to email report because Attachment too big

### ISSUE THREAD

**Issue by ekokristianto** [katalon-studio/katalon-studio#18]
I include report HTML as email attachment
Whenever testcase failed it took screenshot, the email attachment become bigger.
I run test Suite Collection with a lot of testcases.
I got error email failed to sent (size >25Mb) :
System is unable to email report. Reason: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1421)
	at org.apache.commons.mail.Email.send(Email.java:1448)
	at com.kms.katalon.execution.util.MailUtil.sendSummaryMail(MailUtil.java:136)
	at com.kms.katalon.execution.launcher.ReportableLauncher.sendReportEmail(ReportableLauncher.java:158)
	at com.kms.katalon.execution.launcher.ReportableLauncher.sendReport(ReportableLauncher.java:128)
	at com.kms.katalon.execution.launcher.ReportableLauncher.preExecutionComplete(ReportableLauncher.java:81)
	at com.kms.katalon.execution.launcher.ProcessLauncher.onWatchdogComplete(ProcessLauncher.java:171)
	at com.kms.katalon.execution.launcher.LaunchWatchdog.notifyProcessTerminated(LaunchWatchdog.java:135)
	at com.kms.katalon.execution.launcher.LaunchWatchdog.run(LaunchWatchdog.java:65)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.mail.smtp.SMTPSendFailedException: 552-5.2.3 Your message exceeded Google's message size limits. Please visit
552-5.2.3  https://support.google.com/mail/?p=MaxSizeError to view our size
552 5.2.3 guidelines. x194-v6sm27531432pfd.32 - gsmtp

	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:1388)
	at com.sun.mail.smtp.SMTPTransport.finishData(SMTPTransport.java:1215)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:586)
	at javax.mail.Transport.send0(Transport.java:169)
	at javax.mail.Transport.send(Transport.java:98)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1411)
	... 9 more

I suggest split attachment to multiple attachment per testcase so that the size won't be too big in one file.

**Comment by devalex88** [comment]
Gmail has a _total size limit_ for attachments https://support.google.com/mail/?p=MaxSizeError. Splitting attachments won't work.

> You can send up to 25 MB in attachments. If you have more than one attachment, they can't add up to more than 25 MB.

Suggested approach: Add a capability to plugins so that they can upload reports to Google Drive or Katalon Analytics and insert the respective links to report emails.
