### ISSUE TITLE
Can't run tests in Jenkins (docker) Unable to open browser with url: ''

### ISSUE THREAD

**Issue by pavelsmajda** [katalon-studio/katalon-studio#195]
When I try to run tests in Jenkins (docker) then following errors appear:
////////////////////////////////////////////////////////////////////////////////
"Unable to open browser with url: ''"
"Caused by: org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)"
////////////////////////////////////////////////////////////////////////////////
Full log below.

It works in local Jenkins but not working in docker. I can't find any solution for this. 

Do you have any idea how to fix it?

#### Operating System: 
INFO: Katalon Version: 6.3.3
INFO: Command-line arguments: -runMode=console -projectPath=/var/jenkins_home/workspace/Test_Automation -retry=0 -testSuitePath=Test Suites/SmokeTests -executionProfile=default -browserType=Chrome (headless)
INFO: User working dir: /tmp/katalon-5024015883395003540
INFO: User home: /var/jenkins_home
INFO: Java vendor: Oracle Corporation
INFO: Java version: 1.8.0_212
INFO: Local OS: Linux 64bit

#### Environment (for Web testing): Jenkins (docker)
ChromeDriver 76.0.3809.68

#### Steps to reproduce:
- install google chrome browser (not necessary)
- install Jenkins (docker) locally or on server
- attach katalon studio project from git
- install and use katalon studio plugin:
Version: 6.3.3
Command Arguments: -retry=0 -testSuitePath="Test Suites/SmokeTests" -executionProfile="default" -browserType="Chrome (headless)"
- run your tests and see the error.

#### Actual Behavior:
I have no problem to run this locally but when I use jenkins in docker then following error appear:
////////////////////////////////////////////////////////////////////////////////
Test Suites/SmokeTests - Chrome (headless) - 20190911_092001.............0/3(0%)
////////////////////////////////////////////////////////////////////////////////

2019-09-11 09:20:04.876 INFO  c.k.katalon.core.main.TestSuiteExecutor  - START Test Suites/SmokeTests
2019-09-11 09:20:04.917 INFO  c.k.katalon.core.main.TestSuiteExecutor  - hostName = jenkins - a70c34654213
2019-09-11 09:20:04.918 INFO  c.k.katalon.core.main.TestSuiteExecutor  - os = Linux 64bit
2019-09-11 09:20:04.919 INFO  c.k.katalon.core.main.TestSuiteExecutor  - hostAddress = my-ip
2019-09-11 09:20:04.920 INFO  c.k.katalon.core.main.TestSuiteExecutor  - katalonVersion = 6.3.3.11
2019-09-11 09:20:05.315 INFO  c.k.katalon.core.main.TestCaseExecutor   - --------------------
2019-09-11 09:20:05.316 INFO  c.k.katalon.core.main.TestCaseExecutor   - START Test Cases/1 - Smoke.Tests/1.0-TestA
2019-09-11 09:20:05.804 DEBUG testcase.1.0-TestA               - 1: openBrowser("")
2019-09-11 09:20:06.211 INFO  c.k.k.core.webui.driver.DriverFactory    - Starting 'Chrome (headless)' driver
2019-09-11 09:20:06.264 INFO  c.k.k.core.webui.driver.DriverFactory    - Action delay is set to 0 seconds
2019-09-11 09:20:07.411 INFO  c.k.katalon.core.main.TestCaseExecutor   - END Test Cases/1 - Smoke.Tests/1.0-TestA
2019-09-11 09:20:07.425 INFO  c.k.katalon.core.main.TestCaseExecutor   - --------------------
2019-09-11 09:20:07.427 INFO  c.k.katalon.core.main.TestCaseExecutor   - START Test Cases/1 - Smoke.Tests/1.1-TestB
2019-09-11 09:20:07.686 DEBUG testcase.1.1-TestB               - 1: openBrowser("")
2019-09-11 09:20:07.707 INFO  c.k.k.core.webui.driver.DriverFactory    - Starting 'Chrome (headless)' driver
2019-09-11 09:20:07.998 INFO  c.k.katalon.core.main.TestCaseExecutor   - END Test Cases/1 - Smoke.Tests/1.1-TestB
2019-09-11 09:20:08.020 INFO  c.k.katalon.core.main.TestCaseExecutor   - --------------------
2019-09-11 09:20:08.020 INFO  c.k.katalon.core.main.TestCaseExecutor   - START Test Cases/1 - Smoke.Tests/1.2-TestC
2019-09-11 09:20:08.168 DEBUG testcase.1.2-SMK.MNG.Login               - 1: openBrowser("")
2019-09-11 09:20:08.175 INFO  c.k.k.core.webui.driver.DriverFactory    - Starting 'Chrome (headless)' driver
2019-09-11 09:20:08.445 INFO  c.k.katalon.core.main.TestCaseExecutor   - END Test Cases/1 - Smoke.Tests/1.2-TestC
2019-09-11 09:20:08.481 INFO  c.k.katalon.core.main.TestSuiteExecutor  - --------------------
2019-09-11 09:20:08.482 INFO  c.k.katalon.core.main.TestSuiteExecutor  - END Test Suites/SmokeTests
2019-09-11 09:20:08.482 INFO  c.k.katalon.core.main.TestSuiteExecutor  - ====================
Launcher status after execution process completed: Running

////////////////////////////////////////////////////////////////////////////////
Test Suites/SmokeTests - Chrome (headless) - 20190911_092001...........3/3(100%)
////////////////////////////////////////////////////////////////////////////////

Sep 11, 2019 9:20:06 AM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
Starting **ChromeDriver 76.0.3809.68** (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}) on port 17307
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1568193606.629][SEVERE]: bind() failed: Cannot assign requested address (99)
2019-09-11 09:20:07.299 ERROR c.k.k.core.keyword.internal.KeywordMain  - ❌ Unable to open browser with url: '' (Root cause: com.kms.katalon.core.exception.StepFailedException: Unable to open browser with url: ''
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.stepFailed(WebUIKeywordMain.groovy:64)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:26)
	at com.kms.katalon.core.webui.keyword.builtin.OpenBrowserKeyword.openBrowser(OpenBrowserKeyword.groovy:81)
	at com.kms.katalon.core.webui.keyword.builtin.OpenBrowserKeyword.execute(OpenBrowserKeyword.groovy:67)
	at com.kms.katalon.core.keyword.internal.KeywordExecutor.executeKeywordForPlatform(KeywordExecutor.groovy:56)
	at com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords.openBrowser(WebUiBuiltInKeywords.groovy:60)
	at com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords$openBrowser.call(Unknown Source)
	at 1.0-SMK.GRP.Login.run(1.0-SMK.GRP.Login:16)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:337)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:307)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:299)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:233)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:169)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:142)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:91)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:157)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1568193601930.run(TempTestSuite1568193601930.groovy:35)
Caused by: org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'a70c34654213', ip: 'my-ip', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-1090-aws', java.version: '1.8.0_212'
Driver info: driver.version: CChromeDriver
remote stacktrace: #0 0x561a4f6e5749 <unknown>
////////////////////////////////////////////////////////////////////////////////

**When I remove google chrome browser from docker image then tests are failing at:**

ERROR c.k.k.core.keyword.internal.KeywordMain  - ❌ Unable to open browser with url: '' (Root cause: com.kms.katalon.core.exception.StepFailedException: Unable to open browser with url: ''

Caused by: org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary
////////////////////////////////////////////////////////////////////////////////

THANK YOU!

**Comment by xzhang147** [comment]
Same issue here^ Looking for solutions

**Comment by alexzahn** [comment]
Just a guess, but when I see this locally it's because the Chromedriver is mismatched the the Chrome version installed. The Chromedriver version you had listed is a few months old at this point. You'll likely need to manually update the Chromedriver to its latest version until Katalon team does new release with bundled updated Chromedriver.

**Comment by rudreshtrivedi** [comment]
Kindly maintain compatible version of Chrome and Chromedriver

**Comment by tharungaushik** [comment]
Same issue, any solution for the issue

**Comment by hungnt612** [comment]
Looking for solutions
