### ISSUE TITLE
Azure Devops Extension Fails on installation

### ISSUE THREAD

**Issue by somedumbfox** [katalon-studio/katalon-studio#198]
Forgive me if this is the wrong place to place an issue regarding Katalon Studios Azure DevOps Integration. However the forum is rather inactive regarding this particular issue. DevOps will fail on installation and there isn't much documentation in regards in terms of installing the extension. It's assumed it should be a 1-click install with 0 dependencies. However the log suggests that there are dependencies required.

Any information as to what those dependencies are is helpful. We are trying to test Katalon out as a solution for API testing.
#### Operating System: (for example: Windows 10 or OSX Sierra)
Azure DevOps Integration/Windows Datacenter 2012
#### Katalon Studio Version:
Extension Version 
1.0.2
#### Azure Install logs:
9/23/2019 10:01:17 AM - Microsoft VSIX Installer
9/23/2019 10:01:17 AM - -------------------------------------------
9/23/2019 10:01:17 AM - vsixinstaller.exe version:
9/23/2019 10:01:17 AM - 15.9.3041
9/23/2019 10:01:17 AM - -------------------------------------------
9/23/2019 10:01:17 AM - Command line parameters:
9/23/2019 10:01:17 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\50251335\Downloads\katalon-llc.katalon-1.0.2 (1).vsix
9/23/2019 10:01:17 AM - -------------------------------------------
9/23/2019 10:01:17 AM - Microsoft VSIX Installer
9/23/2019 10:01:17 AM - -------------------------------------------
9/23/2019 10:01:19 AM - Initializing Install...
9/23/2019 10:01:21 AM - Extension Details...
9/23/2019 10:01:21 AM - 	Identifier         : katalon
9/23/2019 10:01:21 AM - 	Name               : Katalon for Azure DevOps
9/23/2019 10:01:21 AM - 	Author             : katalon-llc
9/23/2019 10:01:21 AM - 	Version            : 1.0.2
9/23/2019 10:01:21 AM - 	Description        : This plugin is for executing Katalon Studio Projects on Azure Devops
9/23/2019 10:01:21 AM - 	Locale             : en-US
9/23/2019 10:01:21 AM - 	MoreInfoURL        : 
9/23/2019 10:01:21 AM - 	InstalledByMSI     : False
9/23/2019 10:01:21 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
9/23/2019 10:01:21 AM - 
9/23/2019 10:01:22 AM - 	SignatureState     : Unsigned
9/23/2019 10:01:23 AM - 	Supported Products : 
9/23/2019 10:01:23 AM - 		Microsoft.VisualStudio.Services
9/23/2019 10:01:23 AM - 			Version : 
9/23/2019 10:01:23 AM - 
9/23/2019 10:01:23 AM - 	References         : 
9/23/2019 10:01:23 AM - Signature Details...
9/23/2019 10:01:23 AM - 	Extension is not signed.
9/23/2019 10:01:23 AM - 
9/23/2019 10:01:23 AM - Searching for applicable products...
9/23/2019 10:01:23 AM - Found installed product - Microsoft Visual Studio Premium 2013 
9/23/2019 10:01:23 AM - Found installed product - Microsoft Visual Studio Professional 2013
9/23/2019 10:01:23 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
9/23/2019 10:01:23 AM - Found installed product - Microsoft Visual Studio Enterprise 2015
9/23/2019 10:01:23 AM - Found installed product - Microsoft Visual Studio Professional 2015
9/23/2019 10:01:23 AM - Found installed product - Microsoft Visual Studio Community 2015
9/23/2019 10:01:23 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
9/23/2019 10:01:23 AM - Found installed product - Global Location
9/23/2019 10:01:23 AM - Found installed product - ssms
9/23/2019 10:01:23 AM - Found installed product - Visual Studio Enterprise 2017
9/23/2019 10:01:23 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by somedumbfox** [comment]
Slight misunderstanding on how the extension worked. We learned that Katalon has to be installed and run at least once on the target machine in order for the build to succeed. These steps should be added to Katalons Azure DevOps configuration steps.
