### ISSUE TITLE
File upload issue in mac os

### ISSUE THREAD

**Issue by s12jain** [katalon-studio/katalon-studio#28]
Hi, I am not able to test the upload functionality in Katalon studio (version 5.8.6) in Mac on Chrome version 70.0.3538.102 . I am able to record the test successfully but when I am playing the test case, upload window  is open but after that nothing is happened, Katalon studio is not able to select the file and my test case failed. I am not sure what i am doing working, PFB my code and advice.
``` 
WebUI.openBrowser('')

WebUI.navigateToUrl('http://localhost:8091/')

WebUI.maximizeWindow()

WebUI.click(findTestObject('Object Repository/Umang2/Page_EDB Postgres Migration Portal/a_Projects'))

WebUI.click(findTestObject('Object Repository/Umang2/Page_EDB Postgres Migration Portal/a_Assess'))

'Passing the path of the file'
WebUI.uploadFile(findTestObject('Upload File'), '\\\\Users\\\\sanjayjain\\\\Downloads\\\\040818_Multi_9_gen_hr_ddls.sql.txt')
 
'Capturing the file name after upload and storing it in a variable'
FilePath = WebUI.getAttribute(findTestObject('Upload File'), 'value')
 
'Verifying the Actual path and Expected path of file'
WebUI.verifyMatch(FilePath, 'Users\\fakepath\\Desert.txt', false)

WebUI.delay(15)

```
Console output in Katalon Studio
``` 
2-04-2018 12:22:45 PM - [PASSED] - Browser is opened with url: ''
12-04-2018 12:22:45 PM - [END]    - End action : openBrowser
12-04-2018 12:22:45 PM - [START]  - Start action : navigateToUrl
12-04-2018 12:22:45 PM - [INFO]   - Checking url
12-04-2018 12:22:45 PM - [INFO]   - Navigating to 'http://localhost:8091/'
12-04-2018 12:22:46 PM - [PASSED] - Navigate to 'http://localhost:8091/' successfully
12-04-2018 12:22:46 PM - [END]    - End action : navigateToUrl
12-04-2018 12:22:46 PM - [START]  - Start action : maximizeWindow
12-04-2018 12:22:46 PM - [INFO]   - Maximizing current window
12-04-2018 12:22:47 PM - [PASSED] - Current window maximized
12-04-2018 12:22:47 PM - [END]    - End action : maximizeWindow
12-04-2018 12:22:47 PM - [START]  - Start action : click
12-04-2018 12:22:47 PM - [INFO]   - Finding Test Object with id 'Object Repository/Umang2/Page_EDB Postgres Migration Portal/a_Projects'
12-04-2018 12:22:47 PM - [INFO]   - Checking object
12-04-2018 12:22:47 PM - [INFO]   - Checking timeout
12-04-2018 12:22:47 PM - [INFO]   - Finding web element with id: 'Object Repository/Umang2/Page_EDB Postgres Migration Portal/a_Projects' located by 'By.xpath: //div[@id='headerLinks']/div/ul/li/a' in '90' second(s)
12-04-2018 12:22:48 PM - [INFO]   - Found 5 web elements with id: 'Object Repository/Umang2/Page_EDB Postgres Migration Portal/a_Projects' located by 'By.xpath: //div[@id='headerLinks']/div/ul/li/a' in '90' second(s)
12-04-2018 12:22:48 PM - [INFO]   - Clicking on object: 'Object Repository/Umang2/Page_EDB Postgres Migration Portal/a_Projects'
12-04-2018 12:22:48 PM - [PASSED] - Object: 'Object Repository/Umang2/Page_EDB Postgres Migration Portal/a_Projects' is clicked on
12-04-2018 12:22:48 PM - [END]    - End action : click
12-04-2018 12:22:48 PM - [START]  - Start action : click
12-04-2018 12:22:48 PM - [INFO]   - Finding Test Object with id 'Object Repository/Umang2/Page_EDB Postgres Migration Portal/a_Assess'
12-04-2018 12:22:48 PM - [INFO]   - Checking object
12-04-2018 12:22:48 PM - [INFO]   - Checking timeout
12-04-2018 12:22:48 PM - [INFO]   - Finding web element with id: 'Object Repository/Umang2/Page_EDB Postgres Migration Portal/a_Assess' located by 'By.xpath: //div[@id='app']/div/div[2]/div/div[2]/table/tbody/tr/td[8]/span/a' in '90' second(s)
12-04-2018 12:22:49 PM - [INFO]   - Found 10 web elements with id: 'Object Repository/Umang2/Page_EDB Postgres Migration Portal/a_Assess' located by 'By.xpath: //div[@id='app']/div/div[2]/div/div[2]/table/tbody/tr/td[8]/span/a' in '90' second(s)
12-04-2018 12:22:49 PM - [INFO]   - Clicking on object: 'Object Repository/Umang2/Page_EDB Postgres Migration Portal/a_Assess'
12-04-2018 12:22:50 PM - [PASSED] - Object: 'Object Repository/Umang2/Page_EDB Postgres Migration Portal/a_Assess' is clicked on
12-04-2018 12:22:50 PM - [END]    - End action : click
12-04-2018 12:22:50 PM - [START]  - Start action : uploadFile
12-04-2018 12:22:50 PM - [INFO]   - Finding Test Object with id 'Object Repository/Upload File'
12-04-2018 12:22:50 PM - [WARNING] - Test object with id 'Object Repository/Upload File' does not exist
12-04-2018 12:22:50 PM - [INFO]   - Finding Test Object with id 'Object Repository/'
12-04-2018 12:22:50 PM - [WARNING] - Test object with id 'Object Repository/' does not exist
12-04-2018 12:22:50 PM - [INFO]   - Checking object
12-04-2018 12:22:50 PM - [FAILED] - Unable to upload file '\\Users\\sanjayjain\\Downloads\\040818_Multi_9_gen_hr_ddls.sql.txt' to object (Root cause: java.lang.IllegalArgumentException: Object is null)
12-04-2018 12:22:50 PM - [END]    - End action : uploadFile
12-04-2018 12:22:50 PM - [FAILED] - Test Cases/Umang2 FAILED because (of) (Stack trace: com.kms.katalon.core.exception.StepFailedException: Unable to upload file '\\Users\\sanjayjain\\Downloads\\040818_Multi_9_gen_hr_ddls.sql.txt' to object (Root cause: java.lang.IllegalArgumentException: Object is null)
	at com.kms.katalon.core.keyword.internal.KeywordMain.stepFailed(KeywordMain.groovy:36)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.stepFailed(WebUIKeywordMain.groovy:65)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:27)
	at com.kms.katalon.core.webui.keyword.builtin.UploadFileKeyword.uploadFile(UploadFileKeyword.groovy:87)
	at com.kms.katalon.core.webui.keyword.builtin.UploadFileKeyword.execute(UploadFileKeyword.groovy:68)
	at com.kms.katalon.core.keyword.internal.KeywordExecutor.executeKeywordForPlatform(KeywordExecutor.groovy:53)
	at com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords.uploadFile(WebUiBuiltInKeywords.groovy:2945)
	at com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords$uploadFile$3.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at Script1543555874486.run(Script1543555874486.groovy:27)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:183)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:108)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:294)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:264)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:256)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:200)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:99)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:90)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:149)
	at TempTestCase1543906358805.run(TempTestCase1543906358805.groovy:22)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
	at groovy.lang.GroovyShell.run(GroovyShell.java:518)
	at groovy.lang.GroovyShell.run(GroovyShell.java:507)
	at groovy.ui.GroovyMain.processOnce(GroovyMain.java:653)
	at groovy.ui.GroovyMain.run(GroovyMain.java:384)
	at groovy.ui.GroovyMain.process(GroovyMain.java:370)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:129)
	at groovy.ui.GroovyMain.main(GroovyMain.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:109)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)
)
12-04-2018 12:22:50 PM - [END]    - End Test Case : Test Cases/Umang2

```
Vue Js Code
``` 
 <input type="submit" id="uploadButton" v-on:click.prevent="openFileloader" value="Upload DDL" class="btn-input">
          <input type="file" id="fileToLoad"  v-on:change="loadFileAsText" value="Upload File">
```

**Comment by s12jain** [comment]
Hi, please help, I need this urgently.

**Comment by s12jain** [comment]
Is anybody can help on this, I have to submit it urgently. Thanks

**Comment by devalex88** [comment]
@s12jain - the best place to ask this kind of question is at https://forum.katalon.com or https://gitter.im/katalon-studio.

The error indicated that either the test object `Upload File` was missing, or its location was specified incorrectly. The easiest way to find the correct location is to find the corresponding test object, right click on it, and select "Properties".

![image](https://user-images.githubusercontent.com/36872529/49525064-7e96af00-f8df-11e8-9499-9271fe32f227.png)

![image](https://user-images.githubusercontent.com/36872529/49525136-a8e86c80-f8df-11e8-93f6-fe320c485f79.png)

**Comment by s12jain** [comment]
Hi, Please help on this, I need it urgently. Thanks

**Comment by dungleonhart** [comment]
Dear @s12jain,
Have you tried to get help from our Forum and Chat channels yet?
(https://forum.katalon.com, https://gitter.im/katalon-studio)
