### ISSUE TITLE
Wait for element present or other waits not waiting for specified duration in time 

### ISSUE THREAD

**Issue by nagarjunay** [katalon-studio/katalon-studio#309]
#### Katalon Studio logs: !ENTRY org.eclipse.e4.ui.workbench 4 0 2020-04-01 11:19:33.570
!MESSAGE 
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: -1
	at com.kms.katalon.composer.testcase.ast.editors.KeywordComboBoxCellEditorWithContentProposal.doGetValue(KeywordComboBoxCellEditorWithContentProposal.java:34)
	at com.kms.katalon.composer.testcase.editors.TooltipComboBoxCellEditor.applyEditorValueAndDeactivate(TooltipComboBoxCellEditor.java:244)
	at com.kms.katalon.composer.testcase.editors.TooltipComboBoxCellEditor.focusLost(TooltipComboBoxCellEditor.java:269)
	at com.kms.katalon.composer.testcase.editors.ComboBoxCellEditorWithContentProposal.focusLost(ComboBoxCellEditorWithContentProposal.java:45)
	at com.kms.katalon.composer.testcase.editors.TooltipComboBoxCellEditor$4.focusLost(TooltipComboBoxCellEditor.java:166)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:144)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:802)
	at org.eclipse.swt.custom.CCombo.handleFocus(CCombo.java:922)
	at org.eclipse.swt.custom.CCombo$2.handleEvent(CCombo.java:150)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1270)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1078)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2934)
	at org.eclipse.swt.widgets.Widget.wmSetFocus(Widget.java:2437)
	at org.eclipse.swt.widgets.Control.WM_SETFOCUS(Control.java:5446)
	at org.eclipse.swt.widgets.Tree.WM_SETFOCUS(Tree.java:7195)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4869)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6074)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	at org.eclipse.swt.internal.win32.OS.SetFocus(Native Method)
	at org.eclipse.swt.widgets.Tree.WM_LBUTTONDOWN(Tree.java:6761)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4835)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6074)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2552)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3822)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.kms.katalon.core.application.Application.internalRunGUI(Application.java:173)
	at com.kms.katalon.core.application.Application.runGUI(Application.java:163)
	at com.kms.katalon.core.application.Application.start(Application.java:82)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

!ENTRY org.eclipse.e4.ui.workbench 4 0 2020-04-01 11:19:33.576
!MESSAGE 
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: -1
	at com.kms.katalon.composer.testcase.ast.editors.KeywordComboBoxCellEditorWithContentProposal.doGetValue(KeywordComboBoxCellEditorWithContentProposal.java:34)
	at org.eclipse.jface.viewers.CellEditor.getValue(CellEditor.java:486)
	at org.eclipse.jface.viewers.EditingSupport.saveCellEditorValue(EditingSupport.java:112)
	at org.eclipse.jface.viewers.ColumnViewerEditor.saveEditorValue(ColumnViewerEditor.java:453)
	at org.eclipse.jface.viewers.ColumnViewerEditor.applyEditorValue(ColumnViewerEditor.java:309)
	at org.eclipse.jface.viewers.ColumnViewerEditor$1.applyEditorValue(ColumnViewerEditor.java:152)
	at org.eclipse.jface.viewers.CellEditor$1.run(CellEditor.java:336)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.CellEditor.fireApplyEditorValue(CellEditor.java:333)
	at com.kms.katalon.composer.testcase.editors.TooltipComboBoxCellEditor.applyEditorValueAndDeactivate(TooltipComboBoxCellEditor.java:262)
	at com.kms.katalon.composer.testcase.editors.TooltipComboBoxCellEditor.focusLost(TooltipComboBoxCellEditor.java:269)
	at com.kms.katalon.composer.testcase.editors.ComboBoxCellEditorWithContentProposal.focusLost(ComboBoxCellEditorWithContentProposal.java:45)
	at com.kms.katalon.composer.testcase.editors.TooltipComboBoxCellEditor$4.focusLost(TooltipComboBoxCellEditor.java:166)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:144)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:802)
	at org.eclipse.swt.custom.CCombo.handleFocus(CCombo.java:922)
	at org.eclipse.swt.custom.CCombo$2.handleEvent(CCombo.java:150)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1270)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1078)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2934)
	at org.eclipse.swt.widgets.Widget.wmSetFocus(Widget.java:2437)
	at org.eclipse.swt.widgets.Control.WM_SETFOCUS(Control.java:5446)
	at org.eclipse.swt.widgets.Tree.WM_SETFOCUS(Tree.java:7195)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4869)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6074)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	at org.eclipse.swt.internal.win32.OS.SetFocus(Native Method)
	at org.eclipse.swt.widgets.Tree.WM_LBUTTONDOWN(Tree.java:6761)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4835)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6074)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2552)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3822)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.kms.katalon.core.application.Application.internalRunGUI(Application.java:173)
	at com.kms.katalon.core.application.Application.runGUI(Application.java:163)
	at com.kms.katalon.core.application.Application.start(Application.java:82)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

* Windows logs folder: <Katalon Studio folder>\config\.metadata\.log

* MacOS logs folder: file:///Applications/Katalon%20Studio.app/Contents/MacOS/config/.metadata/.plugins/org.eclipse.ui.workbench/log

#### Environment (for Web testing):

Browser and Browser version

#### Environment (for Mobile testing):

* Appium version

* Mobile platform/version under test: (for example: iOS 11 or Android 7)

* Real device or emulator/simulator: (for example: iPhone 6s real or Nexus 6 simulator)

* Xcode version (for iOS): (for example: Xcode 8 or Xcode 11)

* Appium Logs: <Project folder>\.appium

* Application file (.apk/.ipa): (if possible)

#### Steps to reproduce:

Please include an SSCCE (Short, Self Contained, Correct [compilable] example) description http://sscce.org/

If it’s not possible to provide the web page link (for web), please consider creating a reproducible page on https://jsfiddle.net/

Please also provide your test scripts if possible.

**Comment by Padoplin** [comment]
Hi @nagarjunay 

Please tell us more about your issue and the steps for us to reproduce. 

Jass
