### ISSUE TITLE
[Bug] Unable to run Apache Commons RandomUtils command in Web Recorder (WSVerificationExecutor)

### ISSUE THREAD

**Issue by BrandonDudek** [katalon-studio/katalon-studio#422]
- Katalon Studio Version: 7.8.1.208
- OS Version: Windows 10 Home N (19042.685)
- Browser Version: Chrome 87.0.4280.88 (64-bit)

Steps to Reproduce:

1. Create a Test Case
2. Import `org.apache.commons.lang3.RandomUtils`
3. Add a step using RandomUtils
4. Run Test Case in Web Recorder
5. Error:
```
2020-12-22 16:42:03.921 ERROR c.k.k.core.main.WSVerificationExecutor   - ? Verification FAILED.
Reason:
groovy.lang.MissingPropertyException: No such property: RandomUtils for class: WSVerification1608673189436
	at WSVerification1608673189436.run(WSVerification1608673189436:89)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.WSVerificationExecutor.runScript(WSVerificationExecutor.java:178)
	at com.kms.katalon.core.main.WSVerificationExecutor.doExecute(WSVerificationExecutor.java:172)
	at com.kms.katalon.core.main.WSVerificationExecutor.processExecutionPhase(WSVerificationExecutor.java:155)
	at com.kms.katalon.core.main.WSVerificationExecutor.accessMainPhase(WSVerificationExecutor.java:147)
	at com.kms.katalon.core.main.WSVerificationExecutor.execute(WSVerificationExecutor.java:129)
	at com.kms.katalon.core.main.TestCaseMain.runWSVerificationScript(TestCaseMain.java:127)
	at com.kms.katalon.core.main.TestCaseMain$runWSVerificationScript$0.call(Unknown Source)
	at TempTestCase1608673184757.run(TempTestCase1608673184757.groovy:25)
```

Expected behavior: Should Run without issue, just as if I ran it using the Run or Debug commands.

Screenshots:
**Test Case**
![image](https://user-images.githubusercontent.com/19555354/102935394-10949480-4474-11eb-9431-9e2709a6279f.png)

**Web Recorder**
![image](https://user-images.githubusercontent.com/19555354/102935799-d5469580-4474-11eb-9810-77fa93baf59c.png)

**Comment by duyluonganh** [comment]
Hi @BrandonDudek,

We are able to reproduce this issue. We will put this to our backlog to fix in the next releases.

Thanks for your report

**Comment by BrandonDudek** [comment]
Here is another class that causes the Web Recorder to fail: `java.text.DecimalFormat`
