### ISSUE TITLE
Can not set DesiredCapabilities for socksVersion with integer

### ISSUE THREAD

**Issue by huanmai-kms** [katalon-studio/katalon-studio#484]
#### Operating System: (for example: Windows 10 or OSX Sierra)
OSX Big Sur

#### Katalon Studio Version:
8.0.5

#### Katalon Studio logs:

* Windows logs folder: <Katalon Studio folder>\config\.metadata\.log

* MacOS logs folder: file:///Applications/Katalon%20Studio.app/Contents/MacOS/config/.metadata/log
2021-07-12 12:31:30.147 INFO  c.k.katalon.core.main.TestCaseExecutor   - --------------------
2021-07-12 12:31:30.151 INFO  c.k.katalon.core.main.TestCaseExecutor   - START Test Cases/Verify Login Successfully
2021-07-12 12:31:30.961 INFO  c.k.k.core.webui.driver.DriverFactory    - Starting 'Firefox' driver
Jul 12, 2021 12:31:30 PM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
2021-07-12 12:31:31.078 INFO  c.k.k.c.w.util.WebDriverPropertyUtil     - User set preference: ['proxy', '{socksProxy=44.194.100.197:34377, proxyType=manual, socksVersion=5}']
2021-07-12 12:31:31.079 INFO  c.k.k.core.webui.driver.DriverFactory    - Action delay is set to 0 milliseconds
2021-07-12 12:31:31.664 ERROR c.k.k.core.keyword.internal.KeywordMain  - ❌ Unable to open browser with url: 'https://intranet.kms-technology.com' (Root cause: com.kms.katalon.core.exception.StepFailedException: Unable to open browser with url: 'https://intranet.kms-technology.com'
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.stepFailed(WebUIKeywordMain.groovy:64)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:26)
	at com.kms.katalon.core.webui.keyword.builtin.OpenBrowserKeyword.openBrowser(OpenBrowserKeyword.groovy:81)
	at com.kms.katalon.core.webui.keyword.builtin.OpenBrowserKeyword.execute(OpenBrowserKeyword.groovy:67)
	at com.kms.katalon.core.keyword.internal.KeywordExecutor.executeKeywordForPlatform(KeywordExecutor.groovy:73)
	at com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords.openBrowser(WebUiBuiltInKeywords.groovy:64)
	at com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords$openBrowser.call(Unknown Source)
	at NewTestListener.sampleBeforeTestCase(NewTestListener.groovy:34)
	at NewTestListener.invokeMethod(NewTestListener.groovy)
	at com.kms.katalon.core.context.internal.TestHooker.invokeMethod(TestHooker.java:111)
	at com.kms.katalon.core.context.internal.TestHooker.lambda$3(TestHooker.java:95)
	at com.kms.katalon.core.context.internal.TestHooker.invokeContextMethods(TestHooker.java:94)
	at com.kms.katalon.core.context.internal.TestListenerCollector.lambda$3(TestListenerCollector.java:88)
	at com.kms.katalon.core.context.internal.TestListenerCollector.handleListenerEvent(TestListenerCollector.java:85)
	at com.kms.katalon.core.context.internal.ExecutionEventManager.publicEvent(ExecutionEventManager.java:36)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:231)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:142)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:133)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1626067873802.run(TempTestCase1626067873802.groovy:25)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at org.openqa.selenium.Proxy.<init>(Proxy.java:94)
	at org.openqa.selenium.Proxy.extractFrom(Proxy.java:418)
	at org.openqa.selenium.firefox.FirefoxDriver.dropCapabilities(FirefoxDriver.java:261)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at com.kms.katalon.selenium.driver.CFirefoxDriver.<init>(CFirefoxDriver.java:21)
	at com.kms.katalon.core.webui.driver.firefox.CGeckoDriver.<init>(CGeckoDriver.java:12)
	at com.kms.katalon.core.webui.driver.firefox.CGeckoDriver.from(CGeckoDriver.java:17)
	at com.kms.katalon.core.webui.driver.DriverFactory.createNewFirefoxDriver(DriverFactory.java:677)
	at com.kms.katalon.core.webui.driver.DriverFactory.startNewBrowser(DriverFactory.java:349)
	at com.kms.katalon.core.webui.driver.DriverFactory.openWebDriver(DriverFactory.java:245)
	at com.kms.katalon.core.webui.keyword.builtin.OpenBrowserKeyword$_openBrowser_closure1.doCall(OpenBrowserKeyword.groovy:74)
	at com.kms.katalon.core.webui.keyword.builtin.OpenBrowserKeyword$_openBrowser_closure1.call(OpenBrowserKeyword.groovy)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:20)
	... 18 more
)
2021-07-12 12:31:31.673 ERROR c.k.k.core.context.internal.TestHooker   - ❌ com.kms.katalon.core.exception.StepFailedException: Unable to open browser with url: 'https://intranet.kms-technology.com'
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.stepFailed(WebUIKeywordMain.groovy:64)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:26)
	at com.kms.katalon.core.webui.keyword.builtin.OpenBrowserKeyword.openBrowser(OpenBrowserKeyword.groovy:81)
	at com.kms.katalon.core.webui.keyword.builtin.OpenBrowserKeyword.execute(OpenBrowserKeyword.groovy:67)
	at com.kms.katalon.core.keyword.internal.KeywordExecutor.executeKeywordForPlatform(KeywordExecutor.groovy:73)
	at com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords.openBrowser(WebUiBuiltInKeywords.groovy:64)
	at com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords$openBrowser.call(Unknown Source)
	at NewTestListener.sampleBeforeTestCase(NewTestListener.groovy:34)
	at NewTestListener.invokeMethod(NewTestListener.groovy)
	at com.kms.katalon.core.context.internal.TestHooker.invokeMethod(TestHooker.java:111)
	at com.kms.katalon.core.context.internal.TestHooker.lambda$3(TestHooker.java:95)
	at com.kms.katalon.core.context.internal.TestHooker.invokeContextMethods(TestHooker.java:94)
	at com.kms.katalon.core.context.internal.TestListenerCollector.lambda$3(TestListenerCollector.java:88)
	at com.kms.katalon.core.context.internal.TestListenerCollector.handleListenerEvent(TestListenerCollector.java:85)
	at com.kms.katalon.core.context.internal.ExecutionEventManager.publicEvent(ExecutionEventManager.java:36)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:231)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:142)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:133)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1626067873802.run(TempTestCase1626067873802.groovy:25)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at org.openqa.selenium.Proxy.<init>(Proxy.java:94)
	at org.openqa.selenium.Proxy.extractFrom(Proxy.java:418)
	at org.openqa.selenium.firefox.FirefoxDriver.dropCapabilities(FirefoxDriver.java:261)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at com.kms.katalon.selenium.driver.CFirefoxDriver.<init>(CFirefoxDriver.java:21)
	at com.kms.katalon.core.webui.driver.firefox.CGeckoDriver.<init>(CGeckoDriver.java:12)
	at com.kms.katalon.core.webui.driver.firefox.CGeckoDriver.from(CGeckoDriver.java:17)
	at com.kms.katalon.core.webui.driver.DriverFactory.createNewFirefoxDriver(DriverFactory.java:677)
	at com.kms.katalon.core.webui.driver.DriverFactory.startNewBrowser(DriverFactory.java:349)
	at com.kms.katalon.core.webui.driver.DriverFactory.openWebDriver(DriverFactory.java:245)
	at com.kms.katalon.core.webui.keyword.builtin.OpenBrowserKeyword$_openBrowser_closure1.doCall(OpenBrowserKeyword.groovy:74)
	at com.kms.katalon.core.webui.keyword.builtin.OpenBrowserKeyword$_openBrowser_closure1.call(OpenBrowserKeyword.groovy)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:20)
	... 18 more

2021-07-12 12:31:31.715 INFO  com.kms.katalon.core.util.KeywordUtil    - [SAUCELABS] Current run configuration: Firefox
2021-07-12 12:31:31.716 INFO  com.kms.katalon.core.util.KeywordUtil    - [SAUCELABS] Saucelabs Plugin will not attempt to auto update job status and information !
2021-07-12 12:31:32.226 DEBUG testcase.Verify Login Successfully       - 1: setText(findTestObject("Object Repository/Page_Log In - KMS Intranet/input_Username_os_username"), G_Username)
2021-07-12 12:31:32.355 WARN  c.k.k.c.webui.common.WebUiCommonHelper   - [SELF-HEALING] Failed to find element with id 'Object Repository/Page_Log In - KMS Intranet/input_Username_os_username'. Try using Self-healing.
2021-07-12 12:31:32.382 WARN  c.k.k.c.webui.common.WebUiCommonHelper   - [SELF-HEALING] Browser is not opened
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'C02TV0FWHV2F.local', ip: '2405:4803:c779:3f10:9c22:ba4d:4ac7:8fba%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_275'
Driver info: driver.version: unknown
2021-07-12 12:31:32.386 WARN  c.k.k.c.webui.common.WebUiCommonHelper   - [SELF-HEALING] Browser is not opened
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'C02TV0FWHV2F.local', ip: '2405:4803:c779:3f10:9c22:ba4d:4ac7:8fba%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_275'
Driver info: driver.version: unknown
2021-07-12 12:31:32.395 WARN  c.k.k.c.webui.common.WebUiCommonHelper   - [SELF-HEALING] Browser is not opened
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'C02TV0FWHV2F.local', ip: '2405:4803:c779:3f10:9c22:ba4d:4ac7:8fba%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_275'
Driver info: driver.version: unknown
2021-07-12 12:31:32.400 WARN  c.k.k.c.webui.common.WebUiCommonHelper   - [SELF-HEALING] Browser is not opened
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'C02TV0FWHV2F.local', ip: '2405:4803:c779:3f10:9c22:ba4d:4ac7:8fba%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_275'
Driver info: driver.version: unknown
2021-07-12 12:31:32.407 ERROR c.k.k.core.keyword.internal.KeywordMain  - ❌ Unable to set text 'nhutqnguyen' of object 'Object Repository/Page_Log In - KMS Intranet/input_Username_os_username' (Root cause: com.kms.katalon.core.exception.StepFailedException: Unable to set text 'nhutqnguyen' of object 'Object Repository/Page_Log In - KMS Intranet/input_Username_os_username'
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.stepFailed(WebUIKeywordMain.groovy:64)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:26)
	at com.kms.katalon.core.webui.keyword.builtin.SetTextKeyword.setText(SetTextKeyword.groovy:66)
	at com.kms.katalon.core.webui.keyword.builtin.SetTextKeyword.execute(SetTextKeyword.groovy:37)
	at com.kms.katalon.core.keyword.internal.KeywordExecutor.executeKeywordForPlatform(KeywordExecutor.groovy:73)
	at com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords.setText(WebUiBuiltInKeywords.groovy:980)
	at com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords$setText$0.call(Unknown Source)
	at Verify Login Successfully.run(Verify Login Successfully:21)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:369)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:360)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:339)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:331)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:248)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:142)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:133)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1626067873802.run(TempTestCase1626067873802.groovy:25)
Caused by: com.kms.katalon.core.webui.exception.BrowserNotOpenedException: Browser is not opened
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'C02TV0FWHV2F.local', ip: '2405:4803:c779:3f10:9c22:ba4d:4ac7:8fba%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_275'
Driver info: driver.version: unknown
	at com.kms.katalon.core.webui.driver.DriverFactory.verifyWebDriverIsOpen(DriverFactory.java:936)
	at com.kms.katalon.core.webui.driver.DriverFactory.verifyWebDriver(DriverFactory.java:921)
	at com.kms.katalon.core.webui.driver.DriverFactory.getWebDriver(DriverFactory.java:907)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findElementByNormalMethods(WebUiCommonHelper.java:998)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findElementsBySelectedMethod(WebUiCommonHelper.java:909)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findElementsBySelectedMethod(WebUiCommonHelper.java:892)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findElementsBySelectedMethod(WebUiCommonHelper.java:887)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findElementsByDefault(WebUiCommonHelper.java:883)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findElementsWithSelfHealing(WebUiCommonHelper.java:733)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findWebElements(WebUiCommonHelper.java:718)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findWebElement(WebUiCommonHelper.java:1363)
	at com.kms.katalon.core.webui.keyword.internal.WebUIAbstractKeyword.findWebElement(WebUIAbstractKeyword.groovy:27)
	at com.kms.katalon.core.webui.keyword.internal.WebUIAbstractKeyword.findWebElement(WebUIAbstractKeyword.groovy:26)
	at com.kms.katalon.core.webui.keyword.builtin.SetTextKeyword$_setText_closure1.doCall(SetTextKeyword.groovy:51)
	at com.kms.katalon.core.webui.keyword.builtin.SetTextKeyword$_setText_closure1.call(SetTextKeyword.groovy)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:20)
	at com.kms.katalon.core.webui.keyword.builtin.SetTextKeyword.setText(SetTextKeyword.groovy:66)
	at com.kms.katalon.core.webui.keyword.builtin.SetTextKeyword.execute(SetTextKeyword.groovy:37)
	at com.kms.katalon.core.keyword.internal.KeywordExecutor.executeKeywordForPlatform(KeywordExecutor.groovy:73)
	at com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords.setText(WebUiBuiltInKeywords.groovy:980)
	at com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords$setText$0.call(Unknown Source)
	at Script1625628873501.run(Script1625628873501.groovy:21)
	... 11 more
)
2021-07-12 12:31:32.436 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/Verify Login Successfully FAILED.
Reason:
com.kms.katalon.core.exception.StepFailedException: Unable to set text 'nhutqnguyen' of object 'Object Repository/Page_Log In - KMS Intranet/input_Username_os_username'
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.stepFailed(WebUIKeywordMain.groovy:64)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:26)
	at com.kms.katalon.core.webui.keyword.builtin.SetTextKeyword.setText(SetTextKeyword.groovy:66)
	at com.kms.katalon.core.webui.keyword.builtin.SetTextKeyword.execute(SetTextKeyword.groovy:37)
	at com.kms.katalon.core.keyword.internal.KeywordExecutor.executeKeywordForPlatform(KeywordExecutor.groovy:73)
	at com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords.setText(WebUiBuiltInKeywords.groovy:980)
	at com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords$setText$0.call(Unknown Source)
	at Verify Login Successfully.run(Verify Login Successfully:21)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:369)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:360)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:339)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:331)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:248)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:142)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:133)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1626067873802.run(TempTestCase1626067873802.groovy:25)
Caused by: com.kms.katalon.core.webui.exception.BrowserNotOpenedException: Browser is not opened
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'C02TV0FWHV2F.local', ip: '2405:4803:c779:3f10:9c22:ba4d:4ac7:8fba%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_275'
Driver info: driver.version: unknown
	at com.kms.katalon.core.webui.driver.DriverFactory.verifyWebDriverIsOpen(DriverFactory.java:936)
	at com.kms.katalon.core.webui.driver.DriverFactory.verifyWebDriver(DriverFactory.java:921)
	at com.kms.katalon.core.webui.driver.DriverFactory.getWebDriver(DriverFactory.java:907)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findElementByNormalMethods(WebUiCommonHelper.java:998)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findElementsBySelectedMethod(WebUiCommonHelper.java:909)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findElementsBySelectedMethod(WebUiCommonHelper.java:892)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findElementsBySelectedMethod(WebUiCommonHelper.java:887)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findElementsByDefault(WebUiCommonHelper.java:883)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findElementsWithSelfHealing(WebUiCommonHelper.java:733)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findWebElements(WebUiCommonHelper.java:718)
	at com.kms.katalon.core.webui.common.WebUiCommonHelper.findWebElement(WebUiCommonHelper.java:1363)
	at com.kms.katalon.core.webui.keyword.internal.WebUIAbstractKeyword.findWebElement(WebUIAbstractKeyword.groovy:27)
	at com.kms.katalon.core.webui.keyword.internal.WebUIAbstractKeyword.findWebElement(WebUIAbstractKeyword.groovy:26)
	at com.kms.katalon.core.webui.keyword.builtin.SetTextKeyword$_setText_closure1.doCall(SetTextKeyword.groovy:51)
	at com.kms.katalon.core.webui.keyword.builtin.SetTextKeyword$_setText_closure1.call(SetTextKeyword.groovy)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:20)
	... 17 more

2021-07-12 12:31:32.531 INFO  com.kms.katalon.core.util.KeywordUtil    - [SAUCELABS] Current run configuration: Firefox
2021-07-12 12:31:32.532 INFO  c.k.katalon.core.main.TestCaseExecutor   - END Test Cases/Verify Login Successfully

#### Environment (for Web testing):

Browser: Firefox
Browser version: 89.0.2 (64-bit)

#### Environment (for Mobile testing):

* Appium version

* Mobile platform/version under test: (for example: iOS 11 or Android 7)

* Real device or emulator/simulator: (for example: iPhone 6s real or Nexus 6 simulator)

* Xcode version (for iOS): (for example: Xcode 8 or Xcode 11)

* Appium Logs: <Project folder>\.appium

* Application file (.apk/.ipa): (if possible)

#### Steps to reproduce:

1. Go to project and setting like the screenshot
2. Run a test with Firefox browser
3. throw exception and the test is failed

#### Expected Behavior:
Should pass socks proxy information and use proxy information so that the browser can open

#### Actual Behavior:
Error and browser is not opened

#### Screenshots / Videos: (please attach screenshots or videos if necessary to reproduce the issue)
Here is my DesiredCapabilities for Firefox:
<img width="949" alt="image" src="https://user-images.githubusercontent.com/55089709/125235502-c3431c00-e30c-11eb-9be0-062535f056ad.png">

I tried with Number, it adds .0 to socksVersion so it becomes  5.0 and also throw error from driver:

Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
	at org.openqa.selenium.Proxy.<init>(Proxy.java:94)
	at org.openqa.selenium.Proxy.extractFrom(Proxy.java:418)
	at org.openqa.selenium.firefox.FirefoxDriver.dropCapabilities(FirefoxDriver.java:261)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at com.kms.katalon.selenium.driver.CFirefoxDriver.<init>(CFirefoxDriver.java:21)
	at com.kms.katalon.core.webui.driver.firefox.CGeckoDriver.<init>(CGeckoDriver.java:12)
	at com.kms.katalon.core.webui.driver.firefox.CGeckoDriver.from(CGeckoDriver.java:17)
	at com.kms.katalon.core.webui.driver.DriverFactory.createNewFirefoxDriver(DriverFactory.java:677)
	at com.kms.katalon.core.webui.driver.DriverFactory.startNewBrowser(DriverFactory.java:349)
	at com.kms.katalon.core.webui.driver.DriverFactory.openWebDriver(DriverFactory.java:245)
	at com.kms.katalon.core.webui.keyword.builtin.OpenBrowserKeyword$_openBrowser_closure1.doCall(OpenBrowserKeyword.groovy:74)
	at com.kms.katalon.core.webui.keyword.builtin.OpenBrowserKeyword$_openBrowser_closure1.call(OpenBrowserKeyword.groovy)
	at com.kms.katalon.core.webui.keyword.internal.WebUIKeywordMain.runKeyword(WebUIKeywordMain.groovy:20)

**Comment by huanmai-kms** [comment]
This issue also related to the  selenium issue: https://github.com/mablhq/selenium/commit/801be37639e0050d976dc2972fc236da334f175a  which is fixed in PR: https://github.com/mablhq/selenium/commit/801be37639e0050d976dc2972fc236da334f175a  but it has not yet released in version 3.x.x  but release in 4.0.0-beta-4. 

So if we can not upgrade to 4.0.0-beta-4  we should create a patch to fix Proxy class for our own
