### ISSUE TITLE
Unable to resolve third party library in custom keyword in TestOps only

### ISSUE THREAD

**Issue by floifynaresh** [katalon-studio/katalon-studio#529]
#### Katalon Studio logs:

* Windows logs folder: <Katalon Studio folder>\config\.metadata\.log

* MacOS logs folder: file:///Applications/Katalon%20Studio.app/Contents/MacOS/config/.metadata/log

#### Environment (for Web testing):

Browser and Browser version: Google Chrome Version 98.0.4758.102 (Official Build) (x86_64 

#### Steps to reproduce:

I have a custom keyword that imports JSch libraries to create an SSH tunnel. My test works perfectly fine in Katalon Studio. However, i get the following error when running this test in TestOps.

import com.jcraft.jsch.JSch as JSch
import com.jcraft.jsch.Session as Session

02/28/2022 20:34:16 +00:00 - [TEST_CASE][ERROR] - Test Cases/MFATest: Test Cases/MFATest FAILED.
Reason:
java.lang.Error: Unresolved compilation problems: 
	Groovy:unable to resolve class com.jcraft.jsch.JSch
	Groovy:unable to resolve class com.jcraft.jsch.Session

	at floify.Database.DBMS.<init>(DBMS.groovy:26)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:46)
	at MFATest.run(MFATest:34)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:430)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:421)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:400)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:392)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:273)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:202)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:164)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:105)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:185)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1646080451235.run(TempTestSuite1646080451235.groovy:36)

Here is my Custom Keyword groovy class.

package floify.Database

import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint

import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import static com.kms.katalon.core.testobject.ObjectRepository.findWindowsObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testng.keyword.TestNGBuiltinKeywords as TestNGKW
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import com.kms.katalon.core.windows.keyword.WindowsBuiltinKeywords as Windows
import internal.GlobalVariable as GlobalVariable
import org.openqa.selenium.Keys as Keys
import java.sql.Connection as Connection
import java.sql.ResultSet as ResultSet
import com.katalon.plugin.keyword.connection.DBType
import com.katalon.plugin.keyword.connection.DatabaseKeywords
import com.jcraft.jsch.JSch as JSch
import com.jcraft.jsch.Session as Session
import com.kms.katalon.core.annotation.Keyword
import com.katalon.plugin.keyword.connection.ResultSetKeywords

public class DBMS {
	@Keyword
	def String retrieveOneResult( String query) {

		Connection connection = null

		Properties config = new Properties()

		JSch jsch = new JSch()

		int localPort = GlobalVariable.localPort.toInteger()

		int remotePort = 3306

		String sshUser = GlobalVariable.sshUser

		String sshHost = GlobalVariable.sshHost

		String remoteHost = GlobalVariable.remoteHost

		Session session = jsch.getSession(sshUser, sshHost, 22)

		String SshKeyFilepath = GlobalVariable.SshKeyFilepath

		String sshPassword = ''

		jsch.addIdentity(SshKeyFilepath, sshPassword)

		config.put('StrictHostKeyChecking', 'no')

		config.put('ConnectionAttempts', '3')

		session.setConfig(config)

		session.connect()

		System.out.println('SSH Connected')

		int assinged_port = session.setPortForwardingL(localPort, remoteHost, remotePort)
		String value = ""
		try {

			DatabaseKeywords dbk = new DatabaseKeywords()
			connection = dbk.createConnection(DBType.mysql, 'localhost',
					Integer.toString(localPort), GlobalVariable.dbName, GlobalVariable.dbUser, GlobalVariable.dbPassword)

			ResultSet whiteListData = dbk.executeQuery(connection,query)
			ResultSetKeywords rsk = new ResultSetKeywords()
			'Example: Get single cell value using row and column index'
			value = rsk.getSingleCellValue(whiteListData, 1, 1)
			println("Cell value is " + value)
		}
		finally {
			if(connection != null && !connection.isClosed()){
				System.out.println("Closing Database Connection");
				connection.close();
			}
			if(session !=null && session.isConnected()){
				System.out.println("Closing SSH Connection");
				session.disconnect();
			}
		}

		return value
	}
}

#### Expected Behavior: 

Test case should pass without Errors

#### Actual Behavior:

I am seeing java.lang.Error: Unresolved compilation problems: and my test case fails on TestOps.

**Comment by SumeetK-Numeris** [comment]
@floifynaresh Were you able to resolve this?
