### ISSUE TITLE
USE_SYSTEM proxy specification doesn't work

### ISSUE THREAD

**Issue by paddy-hack** [katalon-studio/katalon-studio#600]
I'm using the `katalon-studio/katalon:8.6.0` Docker image.

#### Operating System:

Ubuntu 20.04.5

#### Katalon Studio Version:

8.6.0

#### Katalon Studio logs:
```
cat /tmp/session-53bd31af/.metadata/.log 
katalon.versionNumber=8.6.0
katalon.buildNumber=208
```

#### Environment (for Web testing):

Chrome

#### Environment (for Mobile testing):

Not Applicable

#### Steps to reproduce:

``` sh
export auto_proxy=http://proxy-pac.example.com/proxy.pac
export https_proxy=http://proxy.example.com:8080
export http_proxy=http://proxy.example.com:8080
export no_proxy=localhost,127.0.0.1/8,::1,.example.com,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
docker run --rm -it -e auto_proxy -e https_proy -e http_proxy -e no_proxy katalon-studio/katalon;:8.6.0 bash
```

and then inside the container

``` sh
git clone https://github.com/katalon-studio-samples/ci-samples.git
katalonc.sh -runMode=console -projectPath=/ci-samples/test.prj \
    -testSuitePath="Test Suites/TS_RegressionTest" -browserType="Chrome" \
    -apiKey="$KATALON_API_KEY" -licenseRelease=true -orgID=$KATALON_ORGANIZATION_ID \
    -reportFolder=Reports/ \
    --config -proxy.auth.option=USE_SYSTEM
```

#### Expected Behavior:

Our KRE Floating License is properly activated and the test suite passes.  That is, when activating online, the feedback shows something like

```
Search for valid offline licenses in folder: /root/.katalon/license
The number of valid offline licenses: 0
Start activating online...


INFO: Katalon Version: 8.6.0
INFO: Command-line arguments: -runMode=console -projectPath=/ci-samples/test.prj -testSuitePath=[...] 
INFO: User working dir: /
```

The above is what I get when using the following proxy configuration:

``` 
--config -proxy.auth.option=MANUAL_CONFIG \
    -proxy.auth.server.type=HTTP -proxy.auth.server.address=proxy.example.com -proxy.auth.server.port=8080
```

#### Actual Behavior:

 The feedback shows

```
INFO: [Proxy Configurations]
INFO: > Authentication Proxy: { proxyOption=USE_SYSTEM, proxyServerType=HTTP, proxyServerAddress=, proxyServerPort=0, username=, password=********, executionList="" }
INFO: > System Proxy: { proxyOption=NO_PROXY, proxyServerType=HTTP, proxyServerAddress=, proxyServerPort=0, username=, password=********, executionList="", isApplyToDesiredCapabilities=false }


Activating...
Start getting machine ID on Linux
End getting machine ID on Linux 71740a04f64dc1704672bd5c6412dc6b
Start appending additional signatures
hardwareSerialNumber 
osDependentUsername root
End appending additional signatures 71740a04f64dc1704672bd5c6412dc6b__root
Start activating offline...
Search for valid offline licenses in folder: /root/.katalon/license
The number of valid offline licenses: 0
Start activating online...
java.lang.NumberFormatException: For input string: "org.apache.http.conn.ConnectTimeoutException: Connect to admin.katalon.com:443 [admin.katalon.com/52.87.24.69, admin.katalon.com/3.230.68.202] failed: connect timed out"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.kms.katalon.integration.analytics.providers.TestOpsFeatureActivatorImpl.testConnection(TestOpsFeatureActivatorImpl.java:150)
	at com.kms.katalon.console.application.ConsoleMain.launch(ConsoleMain.java:256)
	at com.kms.katalon.console.application.ConsoleApplicationStarter.start(ConsoleApplicationStarter.java:36)
	at com.kms.katalon.application.Application.runConsole(Application.java:125)
	at com.kms.katalon.application.Application.start(Application.java:88)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

#### Additional Information

Configuring the proxy with `USE_SYSTEM` used to work for us (at least around 2022-03, don't know about later) with `katalon-studio/katalon:8.2.5`.  Testing the above on that image now gives the same results as 8.6.0.

**Comment by paddy-hack** [comment]
For the record, `unset`ting the `auto_proxy` variable and using IP addresses (instead of hostnames) for the `https_proxy` and `http_proxy` did not change my observations.

**Comment by paddy-hack** [comment]
Nor does using ALL_CAPS environment variable names.

**Comment by TriLeKatalon** [comment]
Hi @paddy-hack,
Are you still facing this issue? 
I see in the command, you had a typo on the _https_proxy_ (should be _https_proxy_ instead of _https_proy_) environment variable, don't know if it caused any issues.
`docker run --rm -it -e auto_proxy -e https_proy -e http_proxy -e no_proxy katalon-studio/katalon;:8.6.0 bash`

**Comment by paddy-hack** [comment]
Thanks for following up.  I've reproduced what I originally reported (after fixing up a few more typos).

That is, the results reported above are still present with both `katalonstudio/katalon:8.6.0` and `katalonstudio/katalon8.2.5`.

I saw that `katalonstudio/katalon:8.6.5` is out so I checked that as well, same problem.

**Comment by TriLeKatalon** [comment]
Could you please try with the Katalon Studio to check if your proxy configurations are correct or not? And could you provide us your license status, organizationId, and the user email also!

**Comment by paddy-hack** [comment]
With all due respect, my proxy settings are correct.  I forward my day-to-day environment's settings to the `docker` invocations and would notice right away if there's a problem with them.  The license is valid, the API key and organization ID are correct as well because things work as expected when I set the proxy manually.

On a hunch, I unset my `no_proxy` variable.  That made `USE_SYSTEM` work.  
Digging slightly deeper, it still works with `no_proxy` set as long as I don't include the private IP address ranges, i.e. `10.0.0.0/8,172.16.0.0/12,192.168.0.0/16`.

Looking at the error message again
``` console
java.lang.NumberFormatException: For input string: "org.apache.http.conn.ConnectTimeoutException: Connect to admin.katalon.com:443 [admin.katalon.com/18.233.22.210, admin.katalon.com/52.23.139.120] failed: connect timed out"
```
I think the `java.lang.NumberFormatException` is caused by the `/` used to indicated the range size.  Using IP addresses without a `/` range spec works fine.  However, adding literal IP addresses to cover these ranges is not practical and will likely cause a string size overflow.

Problem is that the applications we need to test may actually need that `no_proxy` value with `/` range specs.  This `no_proxy` value has been working fine with a all the applications we use in our CI/CD pipelines.  Katalon is the first that doesn't.  Please fix the `no_proxy` parsing to support `/` address ranges :bow:

I checked our `git` repositories and found that we added the private IP address ranges during 2022-12.  So that explains why `USE_SYSTEM` used to work for us before that.
