### ISSUE TITLE
 Cannot invoke "com.kms.katalon.core.logging.model.TestSuiteLogRecord.setStatus(boolean)" because "this.suiteLogRecord" is null

### ISSUE THREAD

**Issue by clifmo** [katalon-studio/katalon-studio#624]
I had the same issue with the beta. It's currently not working for me after full release. 

java.lang.NullPointerException: Cannot invoke "com.kms.katalon.core.logging.model.TestSuiteLogRecord.setStatus(boolean)" because "this.suiteLogRecord" is null
	at com.kms.katalon.execution.launcher.ReportableLauncher.preExecutionComplete(ReportableLauncher.java:161)
	at com.kms.katalon.execution.launcher.ProcessLauncher.onWatchdogComplete(ProcessLauncher.java:194)
	at com.kms.katalon.execution.launcher.LaunchWatchdog.notifyProcessTerminated(LaunchWatchdog.java:136)
	at com.kms.katalon.execution.launcher.LaunchWatchdog.run(LaunchWatchdog.java:66)
	at java.base/java.lang.Thread.run(Thread.java:833)

#### Operating System: (for example: Windows 10 or OSX Sierra)
Windows 11
#### Katalon Studio Version:
9.0.0-2235f178
#### Katalon Studio logs:

**Event Logs**

WebView Server has been started on port 28781
Start getting machine ID on Windows
Start appending additional signatures
hardwareSerialNumber 
osDependentUsername xxxxxxxx
End appending additional signatures xxxxxxxxxxxxxxxxx
End getting machine ID on Windows xxxxxxxx
Start checking and mark activated for GUI mode
End checking and mark activated for GUI mode
Your current licensed session is valid until: October 28, 2023 08:59
Start checking license task
com.kms.katalon.composer.artifact has been installed.
Katalon version: 9.0.0
Plugin info URL: https://store.katalon.com/api/products/ks?appVersion=9.0.0&appType=KSE&licenseType=ENTERPRISE
Plugin info: {
  "productId": 34,
  "name": "Excel Keywords",
  "id": 187249
}
Plugin info: {
  "productId": 24,
  "name": "DBMS Keywords",
  "id": 186879
}
Plugin name: Excel Keywords. Is online: true. Plugin location: C:\Users\clif.molina\.katalon\packages\Katalon_Studio_Windows_64-9.0.0\Katalon_Studio_Windows_64-9.0.0\configuration\plugin\install\187249\1.0.2\ExcelKeywords.jar.
Plugin name: DBMS Keywords. Is online: true. Plugin location: C:\Users\clif.molina\.katalon\packages\Katalon_Studio_Windows_64-9.0.0\Katalon_Studio_Windows_64-9.0.0\configuration\plugin\install\186879\1.0.2\katalon-dbms-keywords.jar.
chromedriver is located at default location: C:\Users\clif.molina\.katalon\packages\Katalon_Studio_Windows_64-9.0.0\Katalon_Studio_Windows_64-9.0.0\configuration\resources\drivers\chromedriver_win32\chromedriver.exe. In case your browser is updated to a newer version, please use this command to update chromdriver: --config -webui.autoUpdateDrivers=true
Launcher status after execution process completed: Running

Fri Oct 27 09:01:10 EDT 2023
java.lang.NullPointerException: Cannot invoke "com.kms.katalon.core.logging.model.TestSuiteLogRecord.setStatus(boolean)" because "this.suiteLogRecord" is null
	at com.kms.katalon.execution.launcher.ReportableLauncher.preExecutionComplete(ReportableLauncher.java:161)
	at com.kms.katalon.execution.launcher.ProcessLauncher.onWatchdogComplete(ProcessLauncher.java:194)
	at com.kms.katalon.execution.launcher.LaunchWatchdog.notifyProcessTerminated(LaunchWatchdog.java:136)
	at com.kms.katalon.execution.launcher.LaunchWatchdog.run(LaunchWatchdog.java:66)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Katalon logs do not contain any relevant information. **

!ENTRY org.eclipse.ui 4 0 2023-10-27 08:58:54.681
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
	at org.eclipse.swt.browser.Browser.checkWidget(Browser.java:211)
	at org.eclipse.swt.browser.Browser.setUrl(Browser.java:1154)
	at com.kms.katalon.composer.components.util.ComponentBuilder.lambda$0(ComponentBuilder.java:352)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:166)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:368)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:470)
	at com.kms.katalon.core.application.ApplicationWorkbenchWindowAdvisor.postWindowClose(ApplicationWorkbenchWindowAdvisor.java:91)
	at org.eclipse.ui.internal.WorkbenchWindow.fireWindowClosed(WorkbenchWindow.java:1801)
	at org.eclipse.ui.internal.WorkbenchWindow.hardClose(WorkbenchWindow.java:2114)
	at org.eclipse.ui.internal.WorkbenchWindow.busyClose(WorkbenchWindow.java:1720)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$5(WorkbenchWindow.java:1744)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.WorkbenchWindow.close(WorkbenchWindow.java:1744)
	at org.eclipse.ui.internal.Workbench$11.run(Workbench.java:1107)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.Workbench.busyClose(Workbench.java:1090)
	at org.eclipse.ui.internal.Workbench.lambda$4(Workbench.java:1391)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1391)
	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1367)
	at com.kms.katalon.composer.handlers.QuitHandler.openConfirmMessageDialog(QuitHandler.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at com.kms.katalon.core.application.WorkbenchApplicationStarter.start(WorkbenchApplicationStarter.java:23)
	at com.kms.katalon.application.Application.runGUI(Application.java:195)
	at com.kms.katalon.application.Application.start(Application.java:107)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

!ENTRY org.eclipse.core.resources 2 10035 2023-10-27 08:58:56.122
!MESSAGE The workspace will exit with unsaved changes in this session.
katalon.versionNumber=9.0.0
katalon.buildNumber=212
!SESSION 2023-10-27 08:58:58.790 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.7
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data @noDefault

!ENTRY org.eclipse.core.resources 2 10035 2023-10-27 08:59:04.539
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.eclipse.e4.ui.model.workbench 2 0 2023-10-27 08:59:07.289
!MESSAGE Position '5' defined in 'com.kms.katalon.menu.tools' is no not a valid list position. Valid list positions are [last, first, before:, after:, index:]

!ENTRY org.eclipse.e4.ui.model.workbench 2 0 2023-10-27 08:59:07.296
!MESSAGE Could not find element with Id 'katalon.composer.objectrepository.handledmenuitem.spyweb' in 'com.kms.katalon.menu.spy'

!ENTRY org.eclipse.e4.ui.model.workbench 2 0 2023-10-27 08:59:07.300
!MESSAGE Could not find element with Id 'com.kms.katalon.composer.integration.analytics.handledtoolitem.katalonTestOps' in 'com.kms.katalon.composer.toolbar.execution'

!ENTRY org.eclipse.e4.ui.model.workbench 2 0 2023-10-27 08:59:07.317
!MESSAGE Could not find element with Id 'com.kms.katalon.composer.mobile.dynamicmenucontribution.ios' in 'com.kms.katalon.composer.execution.menu.debug'

!ENTRY org.eclipse.e4.ui.model.workbench 2 0 2023-10-27 08:59:07.320
!MESSAGE Could not find element with Id 'com.kms.katalon.composer.mobile.dynamicmenucontribution.ios' in 'com.kms.katalon.composer.execution.menu.debug'

!ENTRY org.eclipse.egit.ui 2 0 2023-10-27 08:59:13.966
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\clif.molina'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.jface 2 0 2023-10-27 08:59:14.412
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2023-10-27 08:59:14.412
!MESSAGE A conflict occurred for CTRL+R:
Binding(CTRL+R,
	ParameterizedCommand(Command(com.kms.katalon.composer.search.command.showReferences,Show References,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.composer.search.command.showReferences"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,user)
Binding(CTRL+R,
	ParameterizedCommand(Command(com.kms.katalon.composer.search.command.showReferences,Show References,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.composer.search.command.showReferences"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,user)

!ENTRY org.eclipse.jface 2 0 2023-10-27 08:59:14.415
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2023-10-27 08:59:14.415
!MESSAGE A conflict occurred for F5:
Binding(F5,
	ParameterizedCommand(Command(org.eclipse.ui.file.refresh,Refresh,
		Refresh the selected items,
		Category(org.eclipse.ui.category.file,File,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.ui.file.refresh"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(F5,
	ParameterizedCommand(Command(com.kms.katalon.composer.explorer.command.refresh,Explorer Refresh Command,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.composer.explorer.command.refresh"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,user)
Binding(F5,
	ParameterizedCommand(Command(com.kms.katalon.composer.explorer.command.refresh,Explorer Refresh Command,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.composer.explorer.command.refresh"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,user)

!ENTRY org.eclipse.jface 2 0 2023-10-27 08:59:14.419
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2023-10-27 08:59:14.419
!MESSAGE A conflict occurred for CTRL+O:
Binding(CTRL+O,
	ParameterizedCommand(Command(com.kms.katalon.composer.project.command.open,Open Project,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.composer.project.command.open"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,user)
Binding(CTRL+O,
	ParameterizedCommand(Command(com.kms.katalon.composer.project.command.open,Open Project,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.composer.project.command.open"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,user)

!ENTRY org.eclipse.jface 2 0 2023-10-27 08:59:14.423
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2023-10-27 08:59:14.423
!MESSAGE A conflict occurred for ALT+CTRL+C:
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(com.kms.katalon.composer.studioassist.commands.generateCode,Generate Code,
		,
		Category(org.eclipse.core.commands.categories.autogenerated,Uncategorized,Commands that were either auto-generated or have no category,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.composer.studioassist.commands.generateCode"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(com.kms.katalon.command.commandpalette,Command Palette,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.command.commandpalette"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,user)
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(com.kms.katalon.command.commandpalette,Command Palette,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.command.commandpalette"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,user)

!ENTRY org.eclipse.jface 2 0 2023-10-27 08:59:14.426
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2023-10-27 08:59:14.426
!MESSAGE A conflict occurred for CTRL+H:
Binding(CTRL+H,
	ParameterizedCommand(Command(org.eclipse.search.ui.openSearchDialog,Open Search Dialog,
		Open the Search dialog,
		Category(org.eclipse.search.ui.category.search,Search,Search command category,true),
		WorkbenchHandlerServiceHandler("org.eclipse.search.ui.openSearchDialog"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+H,
	ParameterizedCommand(Command(com.kms.katalon.command.search,searchCommand,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.command.search"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,user)
Binding(CTRL+H,
	ParameterizedCommand(Command(com.kms.katalon.command.search,searchCommand,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.command.search"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,user)

!ENTRY org.eclipse.jface 2 0 2023-10-27 08:59:14.435
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2023-10-27 08:59:14.435
!MESSAGE A conflict occurred for CTRL+SHIFT+D:
Binding(CTRL+SHIFT+D,
	ParameterizedCommand(Command(org.eclipse.jdt.debug.ui.commands.Display,Display,
		Display result of evaluating selected text,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		WorkbenchHandlerServiceHandler("org.eclipse.jdt.debug.ui.commands.Display"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow,,,system)
Binding(CTRL+SHIFT+D,
	ParameterizedCommand(Command(com.kms.katalon.composer.execution.command.debug,,
		Debug,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.composer.execution.command.debug"),
		[Parameter(com.kms.katalon.composer.execution.runMode,Run Mode,null,true)],,true),[org.eclipse.core.commands.Parameterization@de6e4672]),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2023-10-27 08:59:14.435
!MESSAGE A conflict occurred for CTRL+V:
Binding(CTRL+V,
	ParameterizedCommand(Command(org.eclipse.ui.edit.paste,Paste,
		Paste from the clipboard,
		Category(org.eclipse.ui.category.edit,Edit,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.ui.edit.paste"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow,,,system)
Binding(CTRL+V,
	ParameterizedCommand(Command(com.kms.katalon.composer.explorer.command.paste,Explorer Paste Command,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.composer.explorer.command.paste"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2023-10-27 08:59:14.435
!MESSAGE A conflict occurred for CTRL+C:
Binding(CTRL+C,
	ParameterizedCommand(Command(org.eclipse.ui.edit.copy,Copy,
		Copy the selection to the clipboard,
		Category(org.eclipse.ui.category.edit,Edit,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.ui.edit.copy"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow,,,system)
Binding(CTRL+C,
	ParameterizedCommand(Command(com.kms.katalon.composer.explorer.command.copy,Explorer Copy Command,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.composer.explorer.command.copy"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2023-10-27 08:59:14.435
!MESSAGE A conflict occurred for DEL:
Binding(DEL,
	ParameterizedCommand(Command(com.kms.katalon.composer.explorer.command.delete,Explorer Delete Command,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.composer.explorer.command.delete"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,system)
Binding(DEL,
	ParameterizedCommand(Command(org.eclipse.ui.edit.delete,Delete,
		Delete the selection,
		Category(org.eclipse.ui.category.edit,Edit,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.ui.edit.delete"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2023-10-27 08:59:14.435
!MESSAGE A conflict occurred for CTRL+X:
Binding(CTRL+X,
	ParameterizedCommand(Command(org.eclipse.ui.edit.cut,Cut,
		Cut the selection to the clipboard,
		Category(org.eclipse.ui.category.edit,Edit,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.ui.edit.cut"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow,,,system)
Binding(CTRL+X,
	ParameterizedCommand(Command(com.kms.katalon.composer.explorer.command.cut,Explorer Cut Command,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.composer.explorer.command.cut"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2023-10-27 08:59:14.435
!MESSAGE A conflict occurred for F2:
Binding(F2,
	ParameterizedCommand(Command(com.kms.katalon.composer.explorer.command.rename,Explorer Rename Command,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.composer.explorer.command.rename"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,system)
Binding(F2,
	ParameterizedCommand(Command(org.eclipse.ui.edit.rename,Rename,
		Rename the selected item,
		Category(org.eclipse.ui.category.file,File,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.ui.edit.rename"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2023-10-27 08:59:14.435
!MESSAGE A conflict occurred for F3:
Binding(F3,
	ParameterizedCommand(Command(com.kms.katalon.composer.explorer.command.open,Explorer Open Command,
		,
		Category(org.eclipse.e4.ui.model.application.MApplication,Application Category,null,true),
		WorkbenchHandlerServiceHandler("com.kms.katalon.composer.explorer.command.open"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.dialogAndWindow ,,,system)
Binding(F3,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.open.editor,Open Declaration,
		Open an editor on the selected element,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.jdt.ui.edit.text.java.open.editor"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

!ENTRY org.eclipse.e4.ui.workbench 4 0 2023-10-27 08:59:21.895
!MESSAGE Could not load codec 'Lucene84'. Did you forget to add lucene-backward-codecs.jar?
!STACK 0
java.lang.IllegalArgumentException: Could not load codec 'Lucene84'. Did you forget to add lucene-backward-codecs.jar?
	at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:515)
	at org.apache.lucene.index.SegmentInfos.parseSegmentInfos(SegmentInfos.java:404)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:363)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:299)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:288)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1081)
	at com.kms.katalon.composer.components.impl.util.EntityIndexingUtil.loadIndexWriter(EntityIndexingUtil.java:93)
	at com.kms.katalon.composer.components.impl.util.EntityIndexingUtil.doIndex(EntityIndexingUtil.java:163)
	at com.kms.katalon.composer.project.handlers.IndexProjectHandler$1.run(IndexProjectHandler.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (e92ae9ed). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(ByteBufferIndexInput(path="C:\Users\clif.molina\AppData\Local\Temp\Katalon\plugins\lucene_8\f00a5db8-550f-4201-9855-bbdd6a32ee54\segments_1")))
		at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:500)
		at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:370)
		... 7 more
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene84' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene94]
	at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:113)
	at org.apache.lucene.codecs.Codec.forName(Codec.java:118)
	at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:511)
	... 9 more

!ENTRY org.eclipse.core.filebuffers 4 0 2023-10-27 08:59:23.712
!MESSAGE The content type with id "org.eclipse.buildship.core.files.gradlebuildscript" specified in the extension point does not exist.

!ENTRY org.eclipse.core.filebuffers 4 0 2023-10-27 08:59:23.717
!MESSAGE The content type with id "org.eclipse.buildship.core.files.gradlebuildscript" specified in the extension point does not exist.

!ENTRY org.eclipse.e4.ui.workbench 1 0 2023-10-27 08:59:25.562
!MESSAGE Reloading plugins.

!ENTRY org.eclipse.e4.ui.workbench 1 0 2023-10-27 08:59:30.881
!MESSAGE Reloaded plugins successfully.

* MacOS logs folder: file:///Applications/Katalon%20Studio.app/Contents/MacOS/config/.metadata/log

#### Steps to reproduce:

Install Katalon 9. Run a simple unit test.

#### Expected Behavior:

Test runs and launches browser.

#### Actual Behavior:

Null pointer in Katalon core.

Fri Oct 27 09:01:10 EDT 2023
java.lang.NullPointerException: Cannot invoke "com.kms.katalon.core.logging.model.TestSuiteLogRecord.setStatus(boolean)" because "this.suiteLogRecord" is null
	at com.kms.katalon.execution.launcher.ReportableLauncher.preExecutionComplete(ReportableLauncher.java:161)
	at com.kms.katalon.execution.launcher.ProcessLauncher.onWatchdogComplete(ProcessLauncher.java:194)
	at com.kms.katalon.execution.launcher.LaunchWatchdog.notifyProcessTerminated(LaunchWatchdog.java:136)
	at com.kms.katalon.execution.launcher.LaunchWatchdog.run(LaunchWatchdog.java:66)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by JHarrisonP74** [comment]
I'm also encountering this issue, it's happening for me when running a test suite in isolation (but strangely some work, others don't) using the Katalon Runtime Engine. This only occurs when upgrading to Katalon 9.1.0, on 8.6.0 it works fine (no changes at all). Additionally, I can run the test as part of a test suite collection without any issues too. Please help/fix!

**Comment by JHarrisonP74** [comment]
@clifmo I've been speaking to Katalon support about this issue and whilst it doesn't resolve the issue completely, you need to do the following:

- Firstly, ensure you have Java JDK 17 or above installed on your machine
- Setup Java 17 as your JAVA_HOME windows variable and ensure your PATH variable for Java is pointing in the right place (check Google for assistance) (this only applies to Windows)
- Add the following to your Katalon command: "--config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true"

This has helped me with the issues I've been encountering. Why the config bit in particular resolves this baffles me, but I've been able to run 90% of my tests now without getting this error.
